//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemInterface.DanskeBankEdiService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class FileServiceFaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoryField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class ResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string senderIdField;
        
        private string requestIdField;
        
        private System.DateTime timestampField;
        
        private string responseCodeField;
        
        private string responseTextField;
        
        private string receiverIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ResponseText {
            get {
                return this.responseTextField;
            }
            set {
                this.responseTextField = value;
                this.RaisePropertyChanged("ResponseText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReceiverId {
            get {
                return this.receiverIdField;
            }
            set {
                this.receiverIdField = value;
                this.RaisePropertyChanged("ReceiverId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class UploadFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseHeader responseHeaderField;
        
        private byte[] applicationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationResponse {
            get {
                return this.applicationResponseField;
            }
            set {
                this.applicationResponseField = value;
                this.RaisePropertyChanged("ApplicationResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string senderIdField;
        
        private string requestIdField;
        
        private System.DateTime timestampField;
        
        private string languageField;
        
        private string userAgentField;
        
        private string receiverIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string UserAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
                this.RaisePropertyChanged("UserAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReceiverId {
            get {
                return this.receiverIdField;
            }
            set {
                this.receiverIdField = value;
                this.RaisePropertyChanged("ReceiverId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class UploadFileRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private byte[] applicationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationRequest {
            get {
                return this.applicationRequestField;
            }
            set {
                this.applicationRequestField = value;
                this.RaisePropertyChanged("ApplicationRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bxd.fi/CorporateFileService", ConfigurationName="DanskeBankEdiService.CorporateFileServicePortType")]
    public interface CorporateFileServicePortType {
        
        // CODEGEN: Generating message contract since the operation uploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SystemInterface.DanskeBankEdiService.FileServiceFaultDetail), Action="", Name="FileServiceFaultElement")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SystemInterface.DanskeBankEdiService.uploadFileResponse1 uploadFile(SystemInterface.DanskeBankEdiService.uploadFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.uploadFileResponse1> uploadFileAsync(SystemInterface.DanskeBankEdiService.uploadFileRequest1 request);
        
        // CODEGEN: Generating message contract since the operation downloadFileList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SystemInterface.DanskeBankEdiService.FileServiceFaultDetail), Action="", Name="FileServiceFaultElement")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SystemInterface.DanskeBankEdiService.downloadFileListResponse1 downloadFileList(SystemInterface.DanskeBankEdiService.downloadFileListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.downloadFileListResponse1> downloadFileListAsync(SystemInterface.DanskeBankEdiService.downloadFileListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation downloadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SystemInterface.DanskeBankEdiService.FileServiceFaultDetail), Action="", Name="FileServiceFaultElement")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SystemInterface.DanskeBankEdiService.downloadFileResponse1 downloadFile(SystemInterface.DanskeBankEdiService.downloadFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.downloadFileResponse1> downloadFileAsync(SystemInterface.DanskeBankEdiService.downloadFileRequest1 request);
        
        // CODEGEN: Generating message contract since the operation deleteFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SystemInterface.DanskeBankEdiService.FileServiceFaultDetail), Action="", Name="FileServiceFaultElement")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SystemInterface.DanskeBankEdiService.deleteFileResponse1 deleteFile(SystemInterface.DanskeBankEdiService.deleteFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.deleteFileResponse1> deleteFileAsync(SystemInterface.DanskeBankEdiService.deleteFileRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUserInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SystemInterface.DanskeBankEdiService.FileServiceFaultDetail), Action="", Name="FileServiceFaultElement")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SystemInterface.DanskeBankEdiService.getUserInfoResponse1 getUserInfo(SystemInterface.DanskeBankEdiService.getUserInfoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.getUserInfoResponse1> getUserInfoAsync(SystemInterface.DanskeBankEdiService.getUserInfoRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.UploadFileRequest uploadFilein;
        
        public uploadFileRequest1() {
        }
        
        public uploadFileRequest1(SystemInterface.DanskeBankEdiService.UploadFileRequest uploadFilein) {
            this.uploadFilein = uploadFilein;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.UploadFileResponse uploadFileout;
        
        public uploadFileResponse1() {
        }
        
        public uploadFileResponse1(SystemInterface.DanskeBankEdiService.UploadFileResponse uploadFileout) {
            this.uploadFileout = uploadFileout;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class DownloadFileListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private byte[] applicationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationRequest {
            get {
                return this.applicationRequestField;
            }
            set {
                this.applicationRequestField = value;
                this.RaisePropertyChanged("ApplicationRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class DownloadFileListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseHeader responseHeaderField;
        
        private byte[] applicationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationResponse {
            get {
                return this.applicationResponseField;
            }
            set {
                this.applicationResponseField = value;
                this.RaisePropertyChanged("ApplicationResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadFileListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.DownloadFileListRequest downloadFileListin;
        
        public downloadFileListRequest1() {
        }
        
        public downloadFileListRequest1(SystemInterface.DanskeBankEdiService.DownloadFileListRequest downloadFileListin) {
            this.downloadFileListin = downloadFileListin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadFileListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.DownloadFileListResponse downloadFileListout;
        
        public downloadFileListResponse1() {
        }
        
        public downloadFileListResponse1(SystemInterface.DanskeBankEdiService.DownloadFileListResponse downloadFileListout) {
            this.downloadFileListout = downloadFileListout;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class DownloadFileRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private byte[] applicationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationRequest {
            get {
                return this.applicationRequestField;
            }
            set {
                this.applicationRequestField = value;
                this.RaisePropertyChanged("ApplicationRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class DownloadFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseHeader responseHeaderField;
        
        private byte[] applicationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationResponse {
            get {
                return this.applicationResponseField;
            }
            set {
                this.applicationResponseField = value;
                this.RaisePropertyChanged("ApplicationResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.DownloadFileRequest downloadFilein;
        
        public downloadFileRequest1() {
        }
        
        public downloadFileRequest1(SystemInterface.DanskeBankEdiService.DownloadFileRequest downloadFilein) {
            this.downloadFilein = downloadFilein;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.DownloadFileResponse downloadFileout;
        
        public downloadFileResponse1() {
        }
        
        public downloadFileResponse1(SystemInterface.DanskeBankEdiService.DownloadFileResponse downloadFileout) {
            this.downloadFileout = downloadFileout;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class DeleteFileRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private byte[] applicationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationRequest {
            get {
                return this.applicationRequestField;
            }
            set {
                this.applicationRequestField = value;
                this.RaisePropertyChanged("ApplicationRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class DeleteFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseHeader responseHeaderField;
        
        private byte[] applicationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationResponse {
            get {
                return this.applicationResponseField;
            }
            set {
                this.applicationResponseField = value;
                this.RaisePropertyChanged("ApplicationResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.DeleteFileRequest deleteFilein;
        
        public deleteFileRequest1() {
        }
        
        public deleteFileRequest1(SystemInterface.DanskeBankEdiService.DeleteFileRequest deleteFilein) {
            this.deleteFilein = deleteFilein;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.DeleteFileResponse deleteFileout;
        
        public deleteFileResponse1() {
        }
        
        public deleteFileResponse1(SystemInterface.DanskeBankEdiService.DeleteFileResponse deleteFileout) {
            this.deleteFileout = deleteFileout;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class GetUserInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private byte[] applicationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationRequest {
            get {
                return this.applicationRequestField;
            }
            set {
                this.applicationRequestField = value;
                this.RaisePropertyChanged("ApplicationRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.bxd.fi")]
    public partial class GetUserInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseHeader responseHeaderField;
        
        private byte[] applicationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ApplicationResponse {
            get {
                return this.applicationResponseField;
            }
            set {
                this.applicationResponseField = value;
                this.RaisePropertyChanged("ApplicationResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.GetUserInfoRequest getUserInfoin;
        
        public getUserInfoRequest1() {
        }
        
        public getUserInfoRequest1(SystemInterface.DanskeBankEdiService.GetUserInfoRequest getUserInfoin) {
            this.getUserInfoin = getUserInfoin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bxd.fi/CorporateFileService", Order=0)]
        public SystemInterface.DanskeBankEdiService.GetUserInfoResponse getUserInfoout;
        
        public getUserInfoResponse1() {
        }
        
        public getUserInfoResponse1(SystemInterface.DanskeBankEdiService.GetUserInfoResponse getUserInfoout) {
            this.getUserInfoout = getUserInfoout;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CorporateFileServicePortTypeChannel : SystemInterface.DanskeBankEdiService.CorporateFileServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorporateFileServicePortTypeClient : System.ServiceModel.ClientBase<SystemInterface.DanskeBankEdiService.CorporateFileServicePortType>, SystemInterface.DanskeBankEdiService.CorporateFileServicePortType {
        
        public CorporateFileServicePortTypeClient() {
        }
        
        public CorporateFileServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorporateFileServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorporateFileServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorporateFileServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SystemInterface.DanskeBankEdiService.uploadFileResponse1 SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.uploadFile(SystemInterface.DanskeBankEdiService.uploadFileRequest1 request) {
            return base.Channel.uploadFile(request);
        }
        
        public SystemInterface.DanskeBankEdiService.UploadFileResponse uploadFile(SystemInterface.DanskeBankEdiService.UploadFileRequest uploadFilein) {
            SystemInterface.DanskeBankEdiService.uploadFileRequest1 inValue = new SystemInterface.DanskeBankEdiService.uploadFileRequest1();
            inValue.uploadFilein = uploadFilein;
            SystemInterface.DanskeBankEdiService.uploadFileResponse1 retVal = ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).uploadFile(inValue);
            return retVal.uploadFileout;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.uploadFileResponse1> SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.uploadFileAsync(SystemInterface.DanskeBankEdiService.uploadFileRequest1 request) {
            return base.Channel.uploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.uploadFileResponse1> uploadFileAsync(SystemInterface.DanskeBankEdiService.UploadFileRequest uploadFilein) {
            SystemInterface.DanskeBankEdiService.uploadFileRequest1 inValue = new SystemInterface.DanskeBankEdiService.uploadFileRequest1();
            inValue.uploadFilein = uploadFilein;
            return ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).uploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SystemInterface.DanskeBankEdiService.downloadFileListResponse1 SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.downloadFileList(SystemInterface.DanskeBankEdiService.downloadFileListRequest1 request) {
            return base.Channel.downloadFileList(request);
        }
        
        public SystemInterface.DanskeBankEdiService.DownloadFileListResponse downloadFileList(SystemInterface.DanskeBankEdiService.DownloadFileListRequest downloadFileListin) {
            SystemInterface.DanskeBankEdiService.downloadFileListRequest1 inValue = new SystemInterface.DanskeBankEdiService.downloadFileListRequest1();
            inValue.downloadFileListin = downloadFileListin;
            SystemInterface.DanskeBankEdiService.downloadFileListResponse1 retVal = ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).downloadFileList(inValue);
            return retVal.downloadFileListout;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.downloadFileListResponse1> SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.downloadFileListAsync(SystemInterface.DanskeBankEdiService.downloadFileListRequest1 request) {
            return base.Channel.downloadFileListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.downloadFileListResponse1> downloadFileListAsync(SystemInterface.DanskeBankEdiService.DownloadFileListRequest downloadFileListin) {
            SystemInterface.DanskeBankEdiService.downloadFileListRequest1 inValue = new SystemInterface.DanskeBankEdiService.downloadFileListRequest1();
            inValue.downloadFileListin = downloadFileListin;
            return ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).downloadFileListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SystemInterface.DanskeBankEdiService.downloadFileResponse1 SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.downloadFile(SystemInterface.DanskeBankEdiService.downloadFileRequest1 request) {
            return base.Channel.downloadFile(request);
        }
        
        public SystemInterface.DanskeBankEdiService.DownloadFileResponse downloadFile(SystemInterface.DanskeBankEdiService.DownloadFileRequest downloadFilein) {
            SystemInterface.DanskeBankEdiService.downloadFileRequest1 inValue = new SystemInterface.DanskeBankEdiService.downloadFileRequest1();
            inValue.downloadFilein = downloadFilein;
            SystemInterface.DanskeBankEdiService.downloadFileResponse1 retVal = ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).downloadFile(inValue);
            return retVal.downloadFileout;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.downloadFileResponse1> SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.downloadFileAsync(SystemInterface.DanskeBankEdiService.downloadFileRequest1 request) {
            return base.Channel.downloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.downloadFileResponse1> downloadFileAsync(SystemInterface.DanskeBankEdiService.DownloadFileRequest downloadFilein) {
            SystemInterface.DanskeBankEdiService.downloadFileRequest1 inValue = new SystemInterface.DanskeBankEdiService.downloadFileRequest1();
            inValue.downloadFilein = downloadFilein;
            return ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).downloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SystemInterface.DanskeBankEdiService.deleteFileResponse1 SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.deleteFile(SystemInterface.DanskeBankEdiService.deleteFileRequest1 request) {
            return base.Channel.deleteFile(request);
        }
        
        public SystemInterface.DanskeBankEdiService.DeleteFileResponse deleteFile(SystemInterface.DanskeBankEdiService.DeleteFileRequest deleteFilein) {
            SystemInterface.DanskeBankEdiService.deleteFileRequest1 inValue = new SystemInterface.DanskeBankEdiService.deleteFileRequest1();
            inValue.deleteFilein = deleteFilein;
            SystemInterface.DanskeBankEdiService.deleteFileResponse1 retVal = ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).deleteFile(inValue);
            return retVal.deleteFileout;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.deleteFileResponse1> SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.deleteFileAsync(SystemInterface.DanskeBankEdiService.deleteFileRequest1 request) {
            return base.Channel.deleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.deleteFileResponse1> deleteFileAsync(SystemInterface.DanskeBankEdiService.DeleteFileRequest deleteFilein) {
            SystemInterface.DanskeBankEdiService.deleteFileRequest1 inValue = new SystemInterface.DanskeBankEdiService.deleteFileRequest1();
            inValue.deleteFilein = deleteFilein;
            return ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).deleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SystemInterface.DanskeBankEdiService.getUserInfoResponse1 SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.getUserInfo(SystemInterface.DanskeBankEdiService.getUserInfoRequest1 request) {
            return base.Channel.getUserInfo(request);
        }
        
        public SystemInterface.DanskeBankEdiService.GetUserInfoResponse getUserInfo(SystemInterface.DanskeBankEdiService.GetUserInfoRequest getUserInfoin) {
            SystemInterface.DanskeBankEdiService.getUserInfoRequest1 inValue = new SystemInterface.DanskeBankEdiService.getUserInfoRequest1();
            inValue.getUserInfoin = getUserInfoin;
            SystemInterface.DanskeBankEdiService.getUserInfoResponse1 retVal = ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).getUserInfo(inValue);
            return retVal.getUserInfoout;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.getUserInfoResponse1> SystemInterface.DanskeBankEdiService.CorporateFileServicePortType.getUserInfoAsync(SystemInterface.DanskeBankEdiService.getUserInfoRequest1 request) {
            return base.Channel.getUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SystemInterface.DanskeBankEdiService.getUserInfoResponse1> getUserInfoAsync(SystemInterface.DanskeBankEdiService.GetUserInfoRequest getUserInfoin) {
            SystemInterface.DanskeBankEdiService.getUserInfoRequest1 inValue = new SystemInterface.DanskeBankEdiService.getUserInfoRequest1();
            inValue.getUserInfoin = getUserInfoin;
            return ((SystemInterface.DanskeBankEdiService.CorporateFileServicePortType)(this)).getUserInfoAsync(inValue);
        }
    }
}
