//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemInterface.KKAdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stamdata", Namespace="http://schemas.datacontract.org/2004/07/KKAdminWcfService")]
    [System.SerializableAttribute()]
    public partial class Stamdata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adresse2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ByNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CprNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FødtDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> GaveBrevUdløbsDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HarGaveBrevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MedlemsNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OprettetAfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OprettetDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SystemInterface.KKAdminService.StatusTypes StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorKredsNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StorKredsNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SøgeNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SystemInterface.KKAdminService.TilknytningType[] TilknytningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ÆndretAfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ÆndretDatoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse1 {
            get {
                return this.Adresse1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse1Field, value) != true)) {
                    this.Adresse1Field = value;
                    this.RaisePropertyChanged("Adresse1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse2 {
            get {
                return this.Adresse2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adresse2Field, value) != true)) {
                    this.Adresse2Field = value;
                    this.RaisePropertyChanged("Adresse2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ByNavn {
            get {
                return this.ByNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.ByNavnField, value) != true)) {
                    this.ByNavnField = value;
                    this.RaisePropertyChanged("ByNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CprNr {
            get {
                return this.CprNrField;
            }
            set {
                if ((object.ReferenceEquals(this.CprNrField, value) != true)) {
                    this.CprNrField = value;
                    this.RaisePropertyChanged("CprNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FødtDato {
            get {
                return this.FødtDatoField;
            }
            set {
                if ((this.FødtDatoField.Equals(value) != true)) {
                    this.FødtDatoField = value;
                    this.RaisePropertyChanged("FødtDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> GaveBrevUdløbsDato {
            get {
                return this.GaveBrevUdløbsDatoField;
            }
            set {
                if ((this.GaveBrevUdløbsDatoField.Equals(value) != true)) {
                    this.GaveBrevUdløbsDatoField = value;
                    this.RaisePropertyChanged("GaveBrevUdløbsDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HarGaveBrev {
            get {
                return this.HarGaveBrevField;
            }
            set {
                if ((this.HarGaveBrevField.Equals(value) != true)) {
                    this.HarGaveBrevField = value;
                    this.RaisePropertyChanged("HarGaveBrev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MedlemsNr {
            get {
                return this.MedlemsNrField;
            }
            set {
                if ((this.MedlemsNrField.Equals(value) != true)) {
                    this.MedlemsNrField = value;
                    this.RaisePropertyChanged("MedlemsNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilNr {
            get {
                return this.MobilNrField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilNrField, value) != true)) {
                    this.MobilNrField = value;
                    this.RaisePropertyChanged("MobilNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notat {
            get {
                return this.NotatField;
            }
            set {
                if ((object.ReferenceEquals(this.NotatField, value) != true)) {
                    this.NotatField = value;
                    this.RaisePropertyChanged("Notat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OprettetAf {
            get {
                return this.OprettetAfField;
            }
            set {
                if ((object.ReferenceEquals(this.OprettetAfField, value) != true)) {
                    this.OprettetAfField = value;
                    this.RaisePropertyChanged("OprettetAf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OprettetDato {
            get {
                return this.OprettetDatoField;
            }
            set {
                if ((this.OprettetDatoField.Equals(value) != true)) {
                    this.OprettetDatoField = value;
                    this.RaisePropertyChanged("OprettetDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostNr {
            get {
                return this.PostNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PostNrField, value) != true)) {
                    this.PostNrField = value;
                    this.RaisePropertyChanged("PostNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowId {
            get {
                return this.RowIdField;
            }
            set {
                if ((this.RowIdField.Equals(value) != true)) {
                    this.RowIdField = value;
                    this.RaisePropertyChanged("RowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SystemInterface.KKAdminService.StatusTypes Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StorKredsNavn {
            get {
                return this.StorKredsNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.StorKredsNavnField, value) != true)) {
                    this.StorKredsNavnField = value;
                    this.RaisePropertyChanged("StorKredsNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StorKredsNr {
            get {
                return this.StorKredsNrField;
            }
            set {
                if ((this.StorKredsNrField.Equals(value) != true)) {
                    this.StorKredsNrField = value;
                    this.RaisePropertyChanged("StorKredsNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SøgeNavn {
            get {
                return this.SøgeNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.SøgeNavnField, value) != true)) {
                    this.SøgeNavnField = value;
                    this.RaisePropertyChanged("SøgeNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SystemInterface.KKAdminService.TilknytningType[] Tilknytning {
            get {
                return this.TilknytningField;
            }
            set {
                if ((object.ReferenceEquals(this.TilknytningField, value) != true)) {
                    this.TilknytningField = value;
                    this.RaisePropertyChanged("Tilknytning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titel {
            get {
                return this.TitelField;
            }
            set {
                if ((object.ReferenceEquals(this.TitelField, value) != true)) {
                    this.TitelField = value;
                    this.RaisePropertyChanged("Titel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ÆndretAf {
            get {
                return this.ÆndretAfField;
            }
            set {
                if ((object.ReferenceEquals(this.ÆndretAfField, value) != true)) {
                    this.ÆndretAfField = value;
                    this.RaisePropertyChanged("ÆndretAf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ÆndretDato {
            get {
                return this.ÆndretDatoField;
            }
            set {
                if ((this.ÆndretDatoField.Equals(value) != true)) {
                    this.ÆndretDatoField = value;
                    this.RaisePropertyChanged("ÆndretDato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusTypes", Namespace="http://schemas.datacontract.org/2004/07/KKAdminWcfService")]
    public enum StatusTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InActive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TilknytningType", Namespace="http://schemas.datacontract.org/2004/07/KKAdminWcfService")]
    [System.SerializableAttribute()]
    public partial class TilknytningType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeKodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeKode {
            get {
                return this.TypeKodeField;
            }
            set {
                if ((this.TypeKodeField.Equals(value) != true)) {
                    this.TypeKodeField = value;
                    this.RaisePropertyChanged("TypeKode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kirkenskorshaer.dk", ConfigurationName="KKAdminService.IKKAdminService")]
    public interface IKKAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kirkenskorshaer.dk/IKKAdminService/GetVersion", ReplyAction="http://www.kirkenskorshaer.dk/IKKAdminService/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kirkenskorshaer.dk/IKKAdminService/GetVersion", ReplyAction="http://www.kirkenskorshaer.dk/IKKAdminService/GetVersionResponse")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kirkenskorshaer.dk/IKKAdminService/GetSomeStamdataByDateWithPaging", ReplyAction="http://www.kirkenskorshaer.dk/IKKAdminService/GetSomeStamdataByDateWithPagingResp" +
            "onse")]
        SystemInterface.KKAdminService.Stamdata[] GetSomeStamdataByDateWithPaging(System.DateTime lastChange, int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kirkenskorshaer.dk/IKKAdminService/GetSomeStamdataByDateWithPaging", ReplyAction="http://www.kirkenskorshaer.dk/IKKAdminService/GetSomeStamdataByDateWithPagingResp" +
            "onse")]
        System.Threading.Tasks.Task<SystemInterface.KKAdminService.Stamdata[]> GetSomeStamdataByDateWithPagingAsync(System.DateTime lastChange, int pageNumber, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKKAdminServiceChannel : SystemInterface.KKAdminService.IKKAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KKAdminServiceClient : System.ServiceModel.ClientBase<SystemInterface.KKAdminService.IKKAdminService>, SystemInterface.KKAdminService.IKKAdminService {
        
        public KKAdminServiceClient() {
        }
        
        public KKAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KKAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KKAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KKAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
        
        public SystemInterface.KKAdminService.Stamdata[] GetSomeStamdataByDateWithPaging(System.DateTime lastChange, int pageNumber, int pageSize) {
            return base.Channel.GetSomeStamdataByDateWithPaging(lastChange, pageNumber, pageSize);
        }
        
        public System.Threading.Tasks.Task<SystemInterface.KKAdminService.Stamdata[]> GetSomeStamdataByDateWithPagingAsync(System.DateTime lastChange, int pageNumber, int pageSize) {
            return base.Channel.GetSomeStamdataByDateWithPagingAsync(lastChange, pageNumber, pageSize);
        }
    }
}
