using System.Collections.Generic;

namespace Utilities.StaticData
{
	public class PostalCity
	{
		public List<KeyValuePair<string, string>> CityPostalCode;

		private PostalCity()
		{
			CityPostalCode = new List<KeyValuePair<string, string>>
			{
				new KeyValuePair<string,string>("0555","Scanning"),
				new KeyValuePair<string,string>("0800","Høje Taastrup Girostrøget 1 BG-Bank A/S"),
				new KeyValuePair<string,string>("0877","Københvn C Havneholmen 33 Aller Press (konkurrencer)"),
				new KeyValuePair<string,string>("0892","Sjælland USF P"),
				new KeyValuePair<string,string>("0893","Sjælland USF B"),
				new KeyValuePair<string,string>("0897","eBrevsprækken"),
				new KeyValuePair<string,string>("0899","Kommuneservice"),
				new KeyValuePair<string,string>("0900","København C"),
				new KeyValuePair<string,string>("0910","København C Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("0917","Københavns Pakkecenter"),
				new KeyValuePair<string,string>("0918","Københavns Pakke BRC"),
				new KeyValuePair<string,string>("0919","Returprint BRC"),
				new KeyValuePair<string,string>("0929","København C Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("0999","København C Emil Holms Kanal 20 DR Byen"),
				new KeyValuePair<string,string>("100","Tórshavn "),
				new KeyValuePair<string,string>("1000","København K Købmagergade 33 Købmagergades Postkontor"),
				new KeyValuePair<string,string>("1001","København K Postboks"),
				new KeyValuePair<string,string>("1002","København K Postboks"),
				new KeyValuePair<string,string>("1003","København K Postboks"),
				new KeyValuePair<string,string>("1004","København K Postboks"),
				new KeyValuePair<string,string>("1005","København K Postboks"),
				new KeyValuePair<string,string>("1006","København K Postboks"),
				new KeyValuePair<string,string>("1007","København K Postboks"),
				new KeyValuePair<string,string>("1008","København K Postboks"),
				new KeyValuePair<string,string>("1009","København K Postboks"),
				new KeyValuePair<string,string>("1010","København K Postboks"),
				new KeyValuePair<string,string>("1011","København K Postboks"),
				new KeyValuePair<string,string>("1012","København K Postboks"),
				new KeyValuePair<string,string>("1013","København K Postboks"),
				new KeyValuePair<string,string>("1014","København K Postboks"),
				new KeyValuePair<string,string>("1015","København K Postboks"),
				new KeyValuePair<string,string>("1016","København K Postboks"),
				new KeyValuePair<string,string>("1017","København K Postboks"),
				new KeyValuePair<string,string>("1018","København K Postboks"),
				new KeyValuePair<string,string>("1019","København K Postboks"),
				new KeyValuePair<string,string>("1020","København K Postboks"),
				new KeyValuePair<string,string>("1021","København K Postboks"),
				new KeyValuePair<string,string>("1022","København K Postboks"),
				new KeyValuePair<string,string>("1023","København K Postboks"),
				new KeyValuePair<string,string>("1024","København K Postboks"),
				new KeyValuePair<string,string>("1025","København K Postboks"),
				new KeyValuePair<string,string>("1026","København K Postboks"),
				new KeyValuePair<string,string>("1045","København K Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("1050","København K Kongens Nytorv"),
				new KeyValuePair<string,string>("1051","København K Nyhavn"),
				new KeyValuePair<string,string>("1052","København K Herluf Trolles Gade"),
				new KeyValuePair<string,string>("1053","København K Cort Adelers Gade"),
				new KeyValuePair<string,string>("1054","København K Peder Skrams Gade"),
				new KeyValuePair<string,string>("1055","København K August Bournonvilles Passage"),
				new KeyValuePair<string,string>("1055","København K Tordenskjoldsgade"),
				new KeyValuePair<string,string>("1056","København K Heibergsgade"),
				new KeyValuePair<string,string>("1057","København K Holbergsgade"),
				new KeyValuePair<string,string>("1058","København K Havnegade"),
				new KeyValuePair<string,string>("1059","København K Niels Juels Gade"),
				new KeyValuePair<string,string>("1060","København K Holmens Kanal"),
				new KeyValuePair<string,string>("1061","København K Ved Stranden"),
				new KeyValuePair<string,string>("1062","København K Boldhusgade"),
				new KeyValuePair<string,string>("1063","København K Laksegade"),
				new KeyValuePair<string,string>("1064","København K Asylgade"),
				new KeyValuePair<string,string>("1065","København K Fortunstræde"),
				new KeyValuePair<string,string>("1066","København K Admiralgade"),
				new KeyValuePair<string,string>("1067","København K Nikolaj Plads"),
				new KeyValuePair<string,string>("1068","København K Nikolajgade"),
				new KeyValuePair<string,string>("1069","København K Bremerholm"),
				new KeyValuePair<string,string>("1070","København K Vingårdstræde"),
				new KeyValuePair<string,string>("1071","København K Dybensgade"),
				new KeyValuePair<string,string>("1072","København K Lille Kirkestræde"),
				new KeyValuePair<string,string>("1073","København K Store Kirkestræde"),
				new KeyValuePair<string,string>("1074","København K Lille Kongensgade"),
				new KeyValuePair<string,string>("1092","København K Holmens Kanal 2-12 Danske Bank A/S"),
				new KeyValuePair<string,string>("1093","København K Havnegade 5 Danmarks Nationalbank"),
				new KeyValuePair<string,string>("1095","København K Kongens Nytorv 13 Magasin du Nord"),
				new KeyValuePair<string,string>("1098","København K Esplanaden 50 A.P. Møller"),
				new KeyValuePair<string,string>("110","Tórshavn Postboks"),
				new KeyValuePair<string,string>("1100","København K Østergade"),
				new KeyValuePair<string,string>("1101","København K Ny Østergade"),
				new KeyValuePair<string,string>("1102","København K Pistolstræde"),
				new KeyValuePair<string,string>("1103","København K Hovedvagtsgade"),
				new KeyValuePair<string,string>("1104","København K Ny Adelgade"),
				new KeyValuePair<string,string>("1105","København K Kristen Bernikows Gade"),
				new KeyValuePair<string,string>("1106","København K Antonigade"),
				new KeyValuePair<string,string>("1107","København K Grønnegade"),
				new KeyValuePair<string,string>("1110","København K Store Regnegade"),
				new KeyValuePair<string,string>("1111","København K Christian IX's Gade"),
				new KeyValuePair<string,string>("1112","København K Pilestræde"),
				new KeyValuePair<string,string>("1113","København K Silkegade"),
				new KeyValuePair<string,string>("1114","København K Kronprinsensgade"),
				new KeyValuePair<string,string>("1115","København K Klareboderne"),
				new KeyValuePair<string,string>("1116","København K Møntergade"),
				new KeyValuePair<string,string>("1117","København K Gammel Mønt"),
				new KeyValuePair<string,string>("1118","København K Sværtegade"),
				new KeyValuePair<string,string>("1119","København K Landemærket"),
				new KeyValuePair<string,string>("1120","København K Vognmagergade"),
				new KeyValuePair<string,string>("1121","København K Lønporten"),
				new KeyValuePair<string,string>("1122","København K Sjæleboderne"),
				new KeyValuePair<string,string>("1123","København K Gothersgade"),
				new KeyValuePair<string,string>("1124","København K Åbenrå"),
				new KeyValuePair<string,string>("1125","København K Suhmsgade"),
				new KeyValuePair<string,string>("1126","København K Pustervig"),
				new KeyValuePair<string,string>("1127","København K Hauser Plads"),
				new KeyValuePair<string,string>("1128","København K Hausergade"),
				new KeyValuePair<string,string>("1129","København K Sankt Gertruds Stræde"),
				new KeyValuePair<string,string>("1130","København K Rosenborggade"),
				new KeyValuePair<string,string>("1131","København K Tornebuskegade"),
				new KeyValuePair<string,string>("1140","København K Møntergade 19 Dagbladet Børsen"),
				new KeyValuePair<string,string>("1147","København K Pilestræde 34 Berlingske Tidende"),
				new KeyValuePair<string,string>("1148","København K Vognmagergade 11 Gutenberghus"),
				new KeyValuePair<string,string>("1150","København K Købmagergade"),
				new KeyValuePair<string,string>("1151","København K Valkendorfsgade"),
				new KeyValuePair<string,string>("1152","København K Løvstræde"),
				new KeyValuePair<string,string>("1153","København K Niels Hemmingsens Gade"),
				new KeyValuePair<string,string>("1154","København K Gråbrødretorv"),
				new KeyValuePair<string,string>("1155","København K Kejsergade"),
				new KeyValuePair<string,string>("1156","København K Gråbrødrestræde"),
				new KeyValuePair<string,string>("1157","København K Klosterstræde"),
				new KeyValuePair<string,string>("1158","København K Skoubogade"),
				new KeyValuePair<string,string>("1159","København K Skindergade"),
				new KeyValuePair<string,string>("1160","København K Amagertorv"),
				new KeyValuePair<string,string>("1161","København K Vimmelskaftet"),
				new KeyValuePair<string,string>("1162","København K Jorcks Passage"),
				new KeyValuePair<string,string>("1163","København K Klostergården"),
				new KeyValuePair<string,string>("1164","København K Nygade"),
				new KeyValuePair<string,string>("1165","København K Nørregade"),
				new KeyValuePair<string,string>("1165","København K Sankt Petri Passage"),
				new KeyValuePair<string,string>("1166","København K Dyrkøb"),
				new KeyValuePair<string,string>("1167","København K Bispetorvet"),
				new KeyValuePair<string,string>("1168","København K Frue Plads"),
				new KeyValuePair<string,string>("1169","København K Store Kannikestræde"),
				new KeyValuePair<string,string>("1170","København K Lille Kannikestræde"),
				new KeyValuePair<string,string>("1171","København K Fiolstræde"),
				new KeyValuePair<string,string>("1172","København K Krystalgade"),
				new KeyValuePair<string,string>("1173","København K Peder Hvitfeldts Stræde"),
				new KeyValuePair<string,string>("1174","København K Rosengården"),
				new KeyValuePair<string,string>("1175","København K Kultorvet"),
				new KeyValuePair<string,string>("1200","København K Højbro Plads"),
				new KeyValuePair<string,string>("1201","København K Læderstræde"),
				new KeyValuePair<string,string>("1202","København K Gammel Strand"),
				new KeyValuePair<string,string>("1203","København K Nybrogade"),
				new KeyValuePair<string,string>("1204","København K Magstræde"),
				new KeyValuePair<string,string>("1205","København K Snaregade"),
				new KeyValuePair<string,string>("1206","København K Naboløs"),
				new KeyValuePair<string,string>("1207","København K Hyskenstræde"),
				new KeyValuePair<string,string>("1208","København K Kompagnistræde"),
				new KeyValuePair<string,string>("1209","København K Badstuestræde"),
				new KeyValuePair<string,string>("1210","København K Knabrostræde"),
				new KeyValuePair<string,string>("1211","København K Brolæggerstræde"),
				new KeyValuePair<string,string>("1212","København K Vindebrogade"),
				new KeyValuePair<string,string>("1213","København K Bertel Thorvaldsens Plads"),
				new KeyValuePair<string,string>("1214","København K Tøjhusgade"),
				new KeyValuePair<string,string>("1215","København K Børsgade"),
				new KeyValuePair<string,string>("1216","København K Slotsholmsgade"),
				new KeyValuePair<string,string>("1217","København K Børsen"),
				new KeyValuePair<string,string>("1218","København K Christiansborg Ridebane"),
				new KeyValuePair<string,string>("1218","København K Christiansborg Slotsplads"),
				new KeyValuePair<string,string>("1218","København K Christiansborg"),
				new KeyValuePair<string,string>("1218","København K Prins Jørgens Gård"),
				new KeyValuePair<string,string>("1218","København K Proviantpassagen"),
				new KeyValuePair<string,string>("1218","København K Rigsdagsgården"),
				new KeyValuePair<string,string>("1219","København K Christians Brygge 1-5 + 8"),
				new KeyValuePair<string,string>("1220","København K Frederiksholms Kanal"),
				new KeyValuePair<string,string>("1221","København K Søren Kierkegaards Plads"),
				new KeyValuePair<string,string>("1240","København K Christiansborg Folketinget"),
				new KeyValuePair<string,string>("1250","København K Sankt Annæ Plads"),
				new KeyValuePair<string,string>("1251","København K Kvæsthusgade"),
				new KeyValuePair<string,string>("1252","København K Kvæsthusbroen"),
				new KeyValuePair<string,string>("1253","København K Toldbodgade"),
				new KeyValuePair<string,string>("1254","København K Lille Strandstræde"),
				new KeyValuePair<string,string>("1255","København K Store Strandstræde"),
				new KeyValuePair<string,string>("1256","København K Amaliegade"),
				new KeyValuePair<string,string>("1257","København K Amalienborg"),
				new KeyValuePair<string,string>("1258","København K Larsens Plads"),
				new KeyValuePair<string,string>("1259","København K Nordre Toldbod"),
				new KeyValuePair<string,string>("1259","København K Trekroner"),
				new KeyValuePair<string,string>("1260","København K Bredgade"),
				new KeyValuePair<string,string>("1261","København K Palægade"),
				new KeyValuePair<string,string>("1263","København K Churchillparken"),
				new KeyValuePair<string,string>("1263","København K Esplanaden"),
				new KeyValuePair<string,string>("1264","København K Store Kongensgade"),
				new KeyValuePair<string,string>("1265","København K Frederiksgade"),
				new KeyValuePair<string,string>("1266","København K Bornholmsgade"),
				new KeyValuePair<string,string>("1267","København K Hammerensgade"),
				new KeyValuePair<string,string>("1268","København K Jens Kofods Gade"),
				new KeyValuePair<string,string>("1270","København K Grønningen"),
				new KeyValuePair<string,string>("1271","København K Poul Ankers Gade"),
				new KeyValuePair<string,string>("1291","København K Sankt Annæ Plads 26-28 J. Lauritzen A/S"),
				new KeyValuePair<string,string>("1300","København K Borgergade"),
				new KeyValuePair<string,string>("1301","København K Landgreven"),
				new KeyValuePair<string,string>("1302","København K Dronningens Tværgade"),
				new KeyValuePair<string,string>("1303","København K Hindegade"),
				new KeyValuePair<string,string>("1304","København K Adelgade"),
				new KeyValuePair<string,string>("1306","København K Kronprinsessegade"),
				new KeyValuePair<string,string>("1307","København K Georg Brandes Plads"),
				new KeyValuePair<string,string>("1307","København K Sølvgade"),
				new KeyValuePair<string,string>("1308","København K Klerkegade"),
				new KeyValuePair<string,string>("1309","København K Rosengade"),
				new KeyValuePair<string,string>("1310","København K Fredericiagade"),
				new KeyValuePair<string,string>("1311","København K Olfert Fischers Gade"),
				new KeyValuePair<string,string>("1312","København K Gammelvagt"),
				new KeyValuePair<string,string>("1313","København K Sankt Pauls Gade"),
				new KeyValuePair<string,string>("1314","København K Sankt Pauls Plads"),
				new KeyValuePair<string,string>("1315","København K Rævegade"),
				new KeyValuePair<string,string>("1316","København K Rigensgade"),
				new KeyValuePair<string,string>("1317","København K Stokhusgade"),
				new KeyValuePair<string,string>("1318","København K Krusemyntegade"),
				new KeyValuePair<string,string>("1319","København K Gernersgade"),
				new KeyValuePair<string,string>("1320","København K Haregade"),
				new KeyValuePair<string,string>("1321","København K Tigergade"),
				new KeyValuePair<string,string>("1322","København K Suensonsgade"),
				new KeyValuePair<string,string>("1323","København K Hjertensfrydsgade"),
				new KeyValuePair<string,string>("1324","København K Elsdyrsgade"),
				new KeyValuePair<string,string>("1325","København K Delfingade"),
				new KeyValuePair<string,string>("1326","København K Krokodillegade"),
				new KeyValuePair<string,string>("1327","København K Vildandegade"),
				new KeyValuePair<string,string>("1328","København K Svanegade"),
				new KeyValuePair<string,string>("1329","København K Timiansgade"),
				new KeyValuePair<string,string>("1349","København K Sølvgade 40 DSB"),
				new KeyValuePair<string,string>("1350","København K Øster Voldgade"),
				new KeyValuePair<string,string>("1352","København K Rørholmsgade"),
				new KeyValuePair<string,string>("1353","København K Øster Farimagsgade 3-15 + 2"),
				new KeyValuePair<string,string>("1354","København K Ole Suhrs Gade"),
				new KeyValuePair<string,string>("1355","København K Gammeltoftsgade"),
				new KeyValuePair<string,string>("1356","København K Bartholinsgade"),
				new KeyValuePair<string,string>("1357","København K Øster Søgade 8-36"),
				new KeyValuePair<string,string>("1358","København K Nørre Voldgade"),
				new KeyValuePair<string,string>("1359","København K Ahlefeldtsgade"),
				new KeyValuePair<string,string>("1359","København K Charlotte Ammundsens Plads"),
				new KeyValuePair<string,string>("1360","København K Frederiksborggade"),
				new KeyValuePair<string,string>("1361","København K Israels Plads"),
				new KeyValuePair<string,string>("1361","København K Linnésgade"),
				new KeyValuePair<string,string>("1362","København K Rømersgade"),
				new KeyValuePair<string,string>("1363","København K Vendersgade"),
				new KeyValuePair<string,string>("1364","København K Nørre Farimagsgade"),
				new KeyValuePair<string,string>("1365","København K Schacksgade"),
				new KeyValuePair<string,string>("1366","København K Nansensgade"),
				new KeyValuePair<string,string>("1367","København K Kjeld Langes Gade"),
				new KeyValuePair<string,string>("1368","København K Turesensgade"),
				new KeyValuePair<string,string>("1369","København K Gyldenløvesgade lige nr."),
				new KeyValuePair<string,string>("1370","København K Nørre Søgade"),
				new KeyValuePair<string,string>("1371","København K Søtorvet"),
				new KeyValuePair<string,string>("1400","København K Knippelsbro"),
				new KeyValuePair<string,string>("1400","København K Torvegade"),
				new KeyValuePair<string,string>("1401","København K Strandgade"),
				new KeyValuePair<string,string>("1402","København K Asiatisk Plads"),
				new KeyValuePair<string,string>("1402","København K David Balfours Gade"),
				new KeyValuePair<string,string>("1402","København K Hammershøi Kaj"),
				new KeyValuePair<string,string>("1402","København K Johan Semps Gade"),
				new KeyValuePair<string,string>("1402","København K Nicolai Eigtveds Gade"),
				new KeyValuePair<string,string>("1403","København K Wilders Plads"),
				new KeyValuePair<string,string>("1404","København K Krøyers Plads"),
				new KeyValuePair<string,string>("1406","København K Christianshavns Kanal"),
				new KeyValuePair<string,string>("1407","København K Bådsmandsstræde"),
				new KeyValuePair<string,string>("1408","København K Wildersgade"),
				new KeyValuePair<string,string>("1409","København K Knippelsbrogade"),
				new KeyValuePair<string,string>("1410","København K Christianshavns Torv"),
				new KeyValuePair<string,string>("1411","København K Applebys Plads"),
				new KeyValuePair<string,string>("1411","København K Langebrogade"),
				new KeyValuePair<string,string>("1412","København K Voldgården"),
				new KeyValuePair<string,string>("1413","København K Ved Kanalen"),
				new KeyValuePair<string,string>("1414","København K Overgaden Neden Vandet"),
				new KeyValuePair<string,string>("1415","København K Overgaden Oven Vandet"),
				new KeyValuePair<string,string>("1416","København K Sankt Annæ Gade"),
				new KeyValuePair<string,string>("1417","København K Mikkel Vibes Gade"),
				new KeyValuePair<string,string>("1418","København K Sofiegade"),
				new KeyValuePair<string,string>("1419","København K Store Søndervoldstræde"),
				new KeyValuePair<string,string>("1420","København K Dronningensgade"),
				new KeyValuePair<string,string>("1421","København K Lille Søndervoldstræde"),
				new KeyValuePair<string,string>("1422","København K Prinsessegade"),
				new KeyValuePair<string,string>("1423","København K Amagergade"),
				new KeyValuePair<string,string>("1424","København K Christianshavns Voldgade"),
				new KeyValuePair<string,string>("1425","København K Ved Volden"),
				new KeyValuePair<string,string>("1426","København K Voldboligerne"),
				new KeyValuePair<string,string>("1427","København K Brobergsgade"),
				new KeyValuePair<string,string>("1428","København K Andreas Bjørns Gade"),
				new KeyValuePair<string,string>("1429","København K Burmeistersgade"),
				new KeyValuePair<string,string>("1430","København K Bodenhoffs Plads"),
				new KeyValuePair<string,string>("1431","København K Islands Plads"),
				new KeyValuePair<string,string>("1432","København K Margretheholmsvej"),
				new KeyValuePair<string,string>("1432","København K Refshalevej"),
				new KeyValuePair<string,string>("1432","København K William Wains Gade"),
				new KeyValuePair<string,string>("1433","København K Christiansholms Ø"),
				new KeyValuePair<string,string>("1433","København K Flakfortet"),
				new KeyValuePair<string,string>("1433","København K Lynetten"),
				new KeyValuePair<string,string>("1433","København K Margretheholm"),
				new KeyValuePair<string,string>("1433","København K Middelgrundsfortet"),
				new KeyValuePair<string,string>("1433","København K Quintus"),
				new KeyValuePair<string,string>("1433","København K Refshaleøen"),
				new KeyValuePair<string,string>("1434","København K Danneskiold-Samsøes Allé"),
				new KeyValuePair<string,string>("1435","København K Philip De Langes Allé"),
				new KeyValuePair<string,string>("1436","København K Arsenalvej"),
				new KeyValuePair<string,string>("1436","København K Halvtolv"),
				new KeyValuePair<string,string>("1436","København K Kuglegården"),
				new KeyValuePair<string,string>("1436","København K Kuglegårdsvej"),
				new KeyValuePair<string,string>("1436","København K Søartillerivej"),
				new KeyValuePair<string,string>("1436","København K Trangravsvej"),
				new KeyValuePair<string,string>("1436","København K Værftsbroen"),
				new KeyValuePair<string,string>("1437","København K Bohlendachvej"),
				new KeyValuePair<string,string>("1437","København K Eik Skaløes Plads"),
				new KeyValuePair<string,string>("1437","København K Fabrikmestervej"),
				new KeyValuePair<string,string>("1437","København K Galionsvej"),
				new KeyValuePair<string,string>("1437","København K Kanonbådsvej"),
				new KeyValuePair<string,string>("1437","København K Leo Mathisens Vej"),
				new KeyValuePair<string,string>("1437","København K Masteskursvej"),
				new KeyValuePair<string,string>("1437","København K Per Knutzons Vej"),
				new KeyValuePair<string,string>("1437","København K Schifters Kvarter"),
				new KeyValuePair<string,string>("1437","København K Stibolts Kvarter"),
				new KeyValuePair<string,string>("1437","København K Takkelloftsvej"),
				new KeyValuePair<string,string>("1437","København K Theodor Christensens Plads"),
				new KeyValuePair<string,string>("1438","København K Benstrups Kvarter"),
				new KeyValuePair<string,string>("1438","København K Dokøvej"),
				new KeyValuePair<string,string>("1438","København K Ekvipagemestervej"),
				new KeyValuePair<string,string>("1438","København K Judichærs Plads"),
				new KeyValuePair<string,string>("1438","København K Orlogsværftvej"),
				new KeyValuePair<string,string>("1439","København K A.H. Vedels Plads"),
				new KeyValuePair<string,string>("1439","København K Bradbænken"),
				new KeyValuePair<string,string>("1439","København K Elefanten"),
				new KeyValuePair<string,string>("1439","København K Eskadrevej"),
				new KeyValuePair<string,string>("1439","København K H.C. Sneedorffs Allé"),
				new KeyValuePair<string,string>("1439","København K Henrik Gerners Plads"),
				new KeyValuePair<string,string>("1439","København K Henrik Spans Vej"),
				new KeyValuePair<string,string>("1439","København K Kongebrovej"),
				new KeyValuePair<string,string>("1439","København K Krudtløbsvej"),
				new KeyValuePair<string,string>("1439","København K Minørvej"),
				new KeyValuePair<string,string>("1439","København K P. Løvenørns Vej"),
				new KeyValuePair<string,string>("1439","København K Spanteloftvej"),
				new KeyValuePair<string,string>("1439","København K Takkeladsvej"),
				new KeyValuePair<string,string>("1439","København K Ved Sixtusbatteriet"),
				new KeyValuePair<string,string>("1439","København K Ved Søminegraven"),
				new KeyValuePair<string,string>("1440","København K Bjørnekloen"),
				new KeyValuePair<string,string>("1440","København K Blå Karamel"),
				new KeyValuePair<string,string>("1440","København K Fabriksområdet"),
				new KeyValuePair<string,string>("1440","København K Fredens Ark"),
				new KeyValuePair<string,string>("1440","København K Løvehuset"),
				new KeyValuePair<string,string>("1440","København K Mælkebøtten"),
				new KeyValuePair<string,string>("1440","København K Mælkevejen"),
				new KeyValuePair<string,string>("1440","København K Nordområdet"),
				new KeyValuePair<string,string>("1440","København K Psyak"),
				new KeyValuePair<string,string>("1440","København K Sydområdet"),
				new KeyValuePair<string,string>("1440","København K Tinghuset"),
				new KeyValuePair<string,string>("1441","København K Midtdyssen"),
				new KeyValuePair<string,string>("1441","København K Norddyssen"),
				new KeyValuePair<string,string>("1441","København K Syddyssen"),
				new KeyValuePair<string,string>("1448","København K Asiatisk Plads 2 Udenrigsministeriet"),
				new KeyValuePair<string,string>("1450","København K Nytorv"),
				new KeyValuePair<string,string>("1451","København K Larslejsstræde"),
				new KeyValuePair<string,string>("1452","København K Teglgårdstræde"),
				new KeyValuePair<string,string>("1453","København K Sankt Peders Stræde"),
				new KeyValuePair<string,string>("1454","København K Larsbjørnsstræde"),
				new KeyValuePair<string,string>("1455","København K Studiestræde 3-49 + 6-40"),
				new KeyValuePair<string,string>("1456","København K Vestergade"),
				new KeyValuePair<string,string>("1457","København K Gammeltorv"),
				new KeyValuePair<string,string>("1458","København K Kattesundet"),
				new KeyValuePair<string,string>("1459","København K Frederiksberggade"),
				new KeyValuePair<string,string>("1460","København K Mikkel Bryggers Gade"),
				new KeyValuePair<string,string>("1461","København K Slutterigade"),
				new KeyValuePair<string,string>("1462","København K Lavendelstræde"),
				new KeyValuePair<string,string>("1463","København K Farvergade"),
				new KeyValuePair<string,string>("1464","København K Hestemøllestræde"),
				new KeyValuePair<string,string>("1465","København K Gåsegade"),
				new KeyValuePair<string,string>("1466","København K Rådhusstræde"),
				new KeyValuePair<string,string>("1467","København K Vandkunsten"),
				new KeyValuePair<string,string>("1468","København K Løngangstræde"),
				new KeyValuePair<string,string>("1470","København K Stormgade 2-14"),
				new KeyValuePair<string,string>("1471","København K Ny Vestergade"),
				new KeyValuePair<string,string>("1472","København K Ny Kongensgade 1-15 + 4-14"),
				new KeyValuePair<string,string>("1473","København K Bryghusgade"),
				new KeyValuePair<string,string>("1500","København V Bernstorffsgade 40 Vesterbro Postkontor"),
				new KeyValuePair<string,string>("1501","København V Postboks"),
				new KeyValuePair<string,string>("1502","København V Postboks"),
				new KeyValuePair<string,string>("1503","København V Postboks"),
				new KeyValuePair<string,string>("1504","København V Postboks"),
				new KeyValuePair<string,string>("1505","København V Postboks"),
				new KeyValuePair<string,string>("1506","København V Postboks"),
				new KeyValuePair<string,string>("1507","København V Postboks"),
				new KeyValuePair<string,string>("1508","København V Postboks"),
				new KeyValuePair<string,string>("1509","København V Postboks"),
				new KeyValuePair<string,string>("1510","København V Postboks"),
				new KeyValuePair<string,string>("1532","København V Kystvejen 26, 2770 Kastrup Internationalt Postcenter, returforsendelser + consignment"),
				new KeyValuePair<string,string>("1533","København V Kystvejen 26, 2770 Kastrup Internationalt Postcenter"),
				new KeyValuePair<string,string>("1550","København V Bag Rådhuset"),
				new KeyValuePair<string,string>("1550","København V Rådhuspladsen"),
				new KeyValuePair<string,string>("1551","København V Jarmers Plads"),
				new KeyValuePair<string,string>("1552","København V Vester Voldgade"),
				new KeyValuePair<string,string>("1553","København V H.C. Andersens Boulevard"),
				new KeyValuePair<string,string>("1553","København V Langebro"),
				new KeyValuePair<string,string>("1554","København V Studiestræde 57-69 + 50-54"),
				new KeyValuePair<string,string>("1555","København V Stormgade 20 + 35"),
				new KeyValuePair<string,string>("1556","København V Dantes Plads"),
				new KeyValuePair<string,string>("1557","København V Ny Kongensgade 19-21 + 18-20"),
				new KeyValuePair<string,string>("1558","København V Christiansborggade"),
				new KeyValuePair<string,string>("1559","København V Christians Brygge 24-30"),
				new KeyValuePair<string,string>("1560","København V Kalvebod Brygge"),
				new KeyValuePair<string,string>("1561","København V Fisketorvet"),
				new KeyValuePair<string,string>("1561","København V Kalvebod Pladsvej"),
				new KeyValuePair<string,string>("1562","København V Hambrosgade"),
				new KeyValuePair<string,string>("1563","København V Otto Mønsteds Plads"),
				new KeyValuePair<string,string>("1564","København V Rysensteensgade"),
				new KeyValuePair<string,string>("1566","København V Tietgensgade 37 Post Danmark A/S"),
				new KeyValuePair<string,string>("1567","København V Polititorvet"),
				new KeyValuePair<string,string>("1568","København V Mitchellsgade"),
				new KeyValuePair<string,string>("1569","København V Edvard Falcks Gade"),
				new KeyValuePair<string,string>("1570","København V Banegårdspladsen"),
				new KeyValuePair<string,string>("1570","København V Københavns Hovedbanegård"),
				new KeyValuePair<string,string>("1571","København V Otto Mønsteds Gade"),
				new KeyValuePair<string,string>("1572","København V Anker Heegaards Gade"),
				new KeyValuePair<string,string>("1573","København V Puggaardsgade"),
				new KeyValuePair<string,string>("1574","København V Niels Brocks Gade"),
				new KeyValuePair<string,string>("1575","København V Ved Glyptoteket"),
				new KeyValuePair<string,string>("1576","København V Stoltenbergsgade"),
				new KeyValuePair<string,string>("1577","København V Arni Magnussons Gade"),
				new KeyValuePair<string,string>("1577","København V Bernstorffsgade"),
				new KeyValuePair<string,string>("1577","København V Carsten Niebuhrs Gade"),
				new KeyValuePair<string,string>("1592","København V Bernstorffsgade 17-19 Københavns Socialdirektorat"),
				new KeyValuePair<string,string>("1599","København V Rådhuspladsen 1 Københavns Rådhus"),
				new KeyValuePair<string,string>("160","Argir "),
				new KeyValuePair<string,string>("1600","København V Gyldenløvesgade ulige nr."),
				new KeyValuePair<string,string>("1601","København V Vester Søgade"),
				new KeyValuePair<string,string>("1602","København V Nyropsgade"),
				new KeyValuePair<string,string>("1603","København V Dahlerupsgade"),
				new KeyValuePair<string,string>("1604","København V Kampmannsgade"),
				new KeyValuePair<string,string>("1605","København V Herholdtsgade"),
				new KeyValuePair<string,string>("1606","København V Vester Farimagsgade"),
				new KeyValuePair<string,string>("1607","København V Staunings Plads"),
				new KeyValuePair<string,string>("1608","København V Jernbanegade"),
				new KeyValuePair<string,string>("1609","København V Axeltorv"),
				new KeyValuePair<string,string>("1610","København V Gammel Kongevej 1-55 + 10"),
				new KeyValuePair<string,string>("1611","København V Hammerichsgade"),
				new KeyValuePair<string,string>("1612","København V Ved Vesterport"),
				new KeyValuePair<string,string>("1613","København V Meldahlsgade"),
				new KeyValuePair<string,string>("1614","København V Trommesalen"),
				new KeyValuePair<string,string>("1615","København V Sankt Jørgens Allé"),
				new KeyValuePair<string,string>("1616","København V Stenosgade"),
				new KeyValuePair<string,string>("1617","København V Bagerstræde"),
				new KeyValuePair<string,string>("1618","København V Tullinsgade"),
				new KeyValuePair<string,string>("1619","København V Værnedamsvej lige nr."),
				new KeyValuePair<string,string>("1620","København V Vesterbrogade 1-149 + 2-150"),
				new KeyValuePair<string,string>("1620","København V Vesterbros Torv"),
				new KeyValuePair<string,string>("1621","København V Frederiksberg Allé 1 - 13B"),
				new KeyValuePair<string,string>("1622","København V Boyesgade ulige nr."),
				new KeyValuePair<string,string>("1623","København V Kingosgade 1-9"),
				new KeyValuePair<string,string>("1624","København V Brorsonsgade"),
				new KeyValuePair<string,string>("1630","København V Vesterbrogade 3 Tivoli A/S"),
				new KeyValuePair<string,string>("1631","København V Herman Triers Plads"),
				new KeyValuePair<string,string>("1632","København V Julius Thomsens Gade lige nr."),
				new KeyValuePair<string,string>("1633","København V Kleinsgade"),
				new KeyValuePair<string,string>("1634","København V Rosenørns Allé 2-18"),
				new KeyValuePair<string,string>("1635","København V Åboulevard 1-13"),
				new KeyValuePair<string,string>("1640","København V Dahlerupsgade 6 Københavns Folkeregister"),
				new KeyValuePair<string,string>("165","Argir Postboks"),
				new KeyValuePair<string,string>("1650","København V Istedgade"),
				new KeyValuePair<string,string>("1651","København V Reventlowsgade"),
				new KeyValuePair<string,string>("1652","København V Colbjørnsensgade"),
				new KeyValuePair<string,string>("1653","København V Helgolandsgade"),
				new KeyValuePair<string,string>("1654","København V Abel Cathrines Gade"),
				new KeyValuePair<string,string>("1655","København V Viktoriagade"),
				new KeyValuePair<string,string>("1656","København V Gasværksvej"),
				new KeyValuePair<string,string>("1657","København V Eskildsgade"),
				new KeyValuePair<string,string>("1658","København V Absalonsgade"),
				new KeyValuePair<string,string>("1659","København V Svendsgade"),
				new KeyValuePair<string,string>("1660","København V Dannebrogsgade"),
				new KeyValuePair<string,string>("1660","København V Otto Krabbes Plads"),
				new KeyValuePair<string,string>("1661","København V Westend"),
				new KeyValuePair<string,string>("1662","København V Saxogade"),
				new KeyValuePair<string,string>("1663","København V Oehlenschlægersgade"),
				new KeyValuePair<string,string>("1664","København V Kaalundsgade"),
				new KeyValuePair<string,string>("1665","København V Valdemarsgade"),
				new KeyValuePair<string,string>("1666","København V Matthæusgade"),
				new KeyValuePair<string,string>("1667","København V Frederiksstadsgade"),
				new KeyValuePair<string,string>("1668","København V Mysundegade"),
				new KeyValuePair<string,string>("1669","København V Flensborggade"),
				new KeyValuePair<string,string>("1670","København V Enghave Plads"),
				new KeyValuePair<string,string>("1671","København V Haderslevgade"),
				new KeyValuePair<string,string>("1671","København V Tove Ditlevsens Plads"),
				new KeyValuePair<string,string>("1672","København V Broagergade"),
				new KeyValuePair<string,string>("1673","København V Ullerupgade"),
				new KeyValuePair<string,string>("1674","København V Enghavevej 1-77 + 2- 78"),
				new KeyValuePair<string,string>("1675","København V Kongshøjgade"),
				new KeyValuePair<string,string>("1676","København V Sankelmarksgade"),
				new KeyValuePair<string,string>("1677","København V Gråstensgade"),
				new KeyValuePair<string,string>("1699","København V Staldgade"),
				new KeyValuePair<string,string>("1700","København V Halmtorvet"),
				new KeyValuePair<string,string>("1701","København V Reverdilsgade"),
				new KeyValuePair<string,string>("1702","København V Stampesgade"),
				new KeyValuePair<string,string>("1703","København V Lille Colbjørnsensgade"),
				new KeyValuePair<string,string>("1704","København V Tietgensgade"),
				new KeyValuePair<string,string>("1705","København V Ingerslevsgade"),
				new KeyValuePair<string,string>("1706","København V Lille Istedgade"),
				new KeyValuePair<string,string>("1707","København V Maria Kirkeplads"),
				new KeyValuePair<string,string>("1708","København V Eriksgade"),
				new KeyValuePair<string,string>("1709","København V Skydebanegade"),
				new KeyValuePair<string,string>("1710","København V Kvægtorvsgade"),
				new KeyValuePair<string,string>("1711","København V Flæsketorvet"),
				new KeyValuePair<string,string>("1711","København V Onkel Dannys Plads"),
				new KeyValuePair<string,string>("1712","København V Høkerboderne"),
				new KeyValuePair<string,string>("1713","København V Kvægtorvet"),
				new KeyValuePair<string,string>("1714","København V Kødboderne"),
				new KeyValuePair<string,string>("1715","København V Slagtehusgade"),
				new KeyValuePair<string,string>("1716","København V Slagterboderne"),
				new KeyValuePair<string,string>("1717","København V Skelbækgade"),
				new KeyValuePair<string,string>("1718","København V Sommerstedgade"),
				new KeyValuePair<string,string>("1719","København V Krusågade"),
				new KeyValuePair<string,string>("1720","København V Sønder Boulevard"),
				new KeyValuePair<string,string>("1721","København V Dybbølsgade"),
				new KeyValuePair<string,string>("1722","København V Godsbanegade"),
				new KeyValuePair<string,string>("1723","København V Letlandsgade"),
				new KeyValuePair<string,string>("1724","København V Estlandsgade"),
				new KeyValuePair<string,string>("1725","København V Esbern Snares Gade"),
				new KeyValuePair<string,string>("1726","København V Arkonagade"),
				new KeyValuePair<string,string>("1727","København V Asger Rygs Gade"),
				new KeyValuePair<string,string>("1728","København V Skjalm Hvides Gade"),
				new KeyValuePair<string,string>("1729","København V Sigerstedgade"),
				new KeyValuePair<string,string>("1730","København V Knud Lavards Gade"),
				new KeyValuePair<string,string>("1731","København V Erik Ejegods Gade"),
				new KeyValuePair<string,string>("1732","København V Bodilsgade"),
				new KeyValuePair<string,string>("1733","København V Palnatokesgade"),
				new KeyValuePair<string,string>("1734","København V Heilsgade"),
				new KeyValuePair<string,string>("1735","København V Røddinggade"),
				new KeyValuePair<string,string>("1736","København V Bevtoftgade"),
				new KeyValuePair<string,string>("1737","København V Bustrupgade"),
				new KeyValuePair<string,string>("1738","København V Stenderupgade"),
				new KeyValuePair<string,string>("1739","København V Enghave Passage"),
				new KeyValuePair<string,string>("1749","København V Rahbeks Allé 3-11"),
				new KeyValuePair<string,string>("175","Kirkjubøur "),
				new KeyValuePair<string,string>("1750","København V Vesterfælledvej 1-91 og 2-56"),
				new KeyValuePair<string,string>("1751","København V Sundevedsgade"),
				new KeyValuePair<string,string>("1752","København V Tøndergade"),
				new KeyValuePair<string,string>("1753","København V Ballumgade"),
				new KeyValuePair<string,string>("1754","København V Hedebygade"),
				new KeyValuePair<string,string>("1755","København V Møgeltøndergade"),
				new KeyValuePair<string,string>("1756","København V Amerikavej"),
				new KeyValuePair<string,string>("1757","København V Trøjborggade"),
				new KeyValuePair<string,string>("1758","København V Lyrskovgade"),
				new KeyValuePair<string,string>("1759","København V Rejsbygade"),
				new KeyValuePair<string,string>("176","Velbastadur "),
				new KeyValuePair<string,string>("1760","København V Ny Carlsberg Vej 1-37 og 2-66"),
				new KeyValuePair<string,string>("1761","København V Ejderstedgade"),
				new KeyValuePair<string,string>("1762","København V Slesvigsgade"),
				new KeyValuePair<string,string>("1763","København V Dannevirkegade"),
				new KeyValuePair<string,string>("1764","København V Alsgade"),
				new KeyValuePair<string,string>("1765","København V Angelgade"),
				new KeyValuePair<string,string>("1766","København V Slien"),
				new KeyValuePair<string,string>("177","Sydradalur, Streymoy "),
				new KeyValuePair<string,string>("1770","København V Carstensgade"),
				new KeyValuePair<string,string>("1771","København V Lundbyesgade"),
				new KeyValuePair<string,string>("1772","København V Ernst Meyers Gade"),
				new KeyValuePair<string,string>("1773","København V Bissensgade"),
				new KeyValuePair<string,string>("1774","København V Küchlersgade"),
				new KeyValuePair<string,string>("1775","København V Freundsgade"),
				new KeyValuePair<string,string>("1777","København V Jerichausgade"),
				new KeyValuePair<string,string>("178","Nordradalur "),
				new KeyValuePair<string,string>("1780","København V"),
				new KeyValuePair<string,string>("1782","København V Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("1785","København V Rådhuspladsen 33 og 37 Politiken og Ekstra Bladet"),
				new KeyValuePair<string,string>("1786","København V Vesterbrogade 8 Nordea"),
				new KeyValuePair<string,string>("1787","København V H.C. Andersens Boulevard 18 Dansk Industri"),
				new KeyValuePair<string,string>("1790","København V"),
				new KeyValuePair<string,string>("1799","København V Bag Elefanterne"),
				new KeyValuePair<string,string>("1799","København V Banevolden 2"),
				new KeyValuePair<string,string>("1799","København V Bjerregårdsvej 5 og 7"),
				new KeyValuePair<string,string>("1799","København V Bryggernes Plads"),
				new KeyValuePair<string,string>("1799","København V Gamle Carlsberg Vej"),
				new KeyValuePair<string,string>("1799","København V Kammasvej 2, 4 og 6"),
				new KeyValuePair<string,string>("1799","København V Ny Carlsberg Vej 39-101 og 68-142"),
				new KeyValuePair<string,string>("1799","København V Ottilia Jacobsens Plads"),
				new KeyValuePair<string,string>("1799","København V Pasteursvej"),
				new KeyValuePair<string,string>("1799","København V Rahbeks Allé 13-15"),
				new KeyValuePair<string,string>("1799","København V Valby Langgade 1"),
				new KeyValuePair<string,string>("1799","København V Vesterfælledvej 58-110"),
				new KeyValuePair<string,string>("180","Kaldbak "),
				new KeyValuePair<string,string>("1800","Frederiksberg C Vesterbrogade 161-191 + 162-208"),
				new KeyValuePair<string,string>("1801","Frederiksberg C Rahbeks Alle 2-36"),
				new KeyValuePair<string,string>("1802","Frederiksberg C Halls Alle"),
				new KeyValuePair<string,string>("1803","Frederiksberg C Brøndsteds Alle"),
				new KeyValuePair<string,string>("1804","Frederiksberg C Bakkegårds Alle"),
				new KeyValuePair<string,string>("1805","Frederiksberg C Kammasvej 3"),
				new KeyValuePair<string,string>("1806","Frederiksberg C Jacobys Alle"),
				new KeyValuePair<string,string>("1807","Frederiksberg C Schlegels Alle"),
				new KeyValuePair<string,string>("1808","Frederiksberg C Asmussens Alle"),
				new KeyValuePair<string,string>("1809","Frederiksberg C Frydendalsvej"),
				new KeyValuePair<string,string>("1810","Frederiksberg C Platanvej"),
				new KeyValuePair<string,string>("1811","Frederiksberg C Asgårdsvej"),
				new KeyValuePair<string,string>("1812","Frederiksberg C Kochsvej"),
				new KeyValuePair<string,string>("1813","Frederiksberg C Henrik Ibsens Vej"),
				new KeyValuePair<string,string>("1814","Frederiksberg C Carit Etlars Vej"),
				new KeyValuePair<string,string>("1815","Frederiksberg C Paludan Müllers Vej"),
				new KeyValuePair<string,string>("1816","Frederiksberg C Engtoftevej"),
				new KeyValuePair<string,string>("1817","Frederiksberg C Carl Bernhards Vej"),
				new KeyValuePair<string,string>("1818","Frederiksberg C Kingosgade 8-10 + 11-17"),
				new KeyValuePair<string,string>("1819","Frederiksberg C Værnedamsvej ulige nr."),
				new KeyValuePair<string,string>("1820","Frederiksberg C Frederiksberg Allé 15-63 + 2-104"),
				new KeyValuePair<string,string>("1822","Frederiksberg C Boyesgade lige nr."),
				new KeyValuePair<string,string>("1823","Frederiksberg C Haveselskabetsvej"),
				new KeyValuePair<string,string>("1824","Frederiksberg C Sankt Thomas Allé"),
				new KeyValuePair<string,string>("1825","Frederiksberg C Hauchsvej"),
				new KeyValuePair<string,string>("1826","Frederiksberg C Alhambravej"),
				new KeyValuePair<string,string>("1827","Frederiksberg C Mynstersvej"),
				new KeyValuePair<string,string>("1828","Frederiksberg C Martensens Alle"),
				new KeyValuePair<string,string>("1829","Frederiksberg C Madvigs Alle"),
				new KeyValuePair<string,string>("1835","Frederiksberg C Postboks Inkl. Frederiksberg C Postkontor"),
				new KeyValuePair<string,string>("185","Kaldbaksbotnur "),
				new KeyValuePair<string,string>("1850","Frederiksberg C Gammel Kongevej 85-179 + 60-178"),
				new KeyValuePair<string,string>("1851","Frederiksberg C Nyvej"),
				new KeyValuePair<string,string>("1852","Frederiksberg C Amicisvej"),
				new KeyValuePair<string,string>("1853","Frederiksberg C Maglekildevej"),
				new KeyValuePair<string,string>("1854","Frederiksberg C Dr. Priemes Vej"),
				new KeyValuePair<string,string>("1855","Frederiksberg C Hollændervej"),
				new KeyValuePair<string,string>("1856","Frederiksberg C Edisonsvej"),
				new KeyValuePair<string,string>("1857","Frederiksberg C Hortensiavej"),
				new KeyValuePair<string,string>("186","Sund "),
				new KeyValuePair<string,string>("1860","Frederiksberg C Christian Winthers Vej"),
				new KeyValuePair<string,string>("1861","Frederiksberg C Sagasvej"),
				new KeyValuePair<string,string>("1862","Frederiksberg C Rathsacksvej"),
				new KeyValuePair<string,string>("1863","Frederiksberg C Ceresvej"),
				new KeyValuePair<string,string>("1864","Frederiksberg C Grundtvigsvej"),
				new KeyValuePair<string,string>("1865","Frederiksberg C Grundtvigs Sidevej"),
				new KeyValuePair<string,string>("1866","Frederiksberg C Henrik Steffens Vej"),
				new KeyValuePair<string,string>("1867","Frederiksberg C Acaciavej"),
				new KeyValuePair<string,string>("1868","Frederiksberg C Bianco Lunos Alle"),
				new KeyValuePair<string,string>("187","Hvitanes "),
				new KeyValuePair<string,string>("1870","Frederiksberg C Bülowsvej"),
				new KeyValuePair<string,string>("1871","Frederiksberg C Thorvaldsensvej"),
				new KeyValuePair<string,string>("1872","Frederiksberg C Bomhoffs Have"),
				new KeyValuePair<string,string>("1873","Frederiksberg C Helenevej"),
				new KeyValuePair<string,string>("1874","Frederiksberg C Harsdorffsvej"),
				new KeyValuePair<string,string>("1875","Frederiksberg C Amalievej"),
				new KeyValuePair<string,string>("1876","Frederiksberg C Kastanievej"),
				new KeyValuePair<string,string>("1877","Frederiksberg C Lindevej"),
				new KeyValuePair<string,string>("1878","Frederiksberg C Uraniavej"),
				new KeyValuePair<string,string>("1879","Frederiksberg C H.C. Ørsteds Vej"),
				new KeyValuePair<string,string>("188","Hoyvík "),
				new KeyValuePair<string,string>("1900","Frederiksberg C Vodroffsvej"),
				new KeyValuePair<string,string>("1901","Frederiksberg C Tårnborgvej"),
				new KeyValuePair<string,string>("1902","Frederiksberg C Lykkesholms Alle"),
				new KeyValuePair<string,string>("1903","Frederiksberg C Sankt Knuds Vej"),
				new KeyValuePair<string,string>("1904","Frederiksberg C Forhåbningsholms Allé"),
				new KeyValuePair<string,string>("1905","Frederiksberg C Svanholmsvej"),
				new KeyValuePair<string,string>("1906","Frederiksberg C Schønbergsgade"),
				new KeyValuePair<string,string>("1908","Frederiksberg C Prinsesse Maries Alle"),
				new KeyValuePair<string,string>("1909","Frederiksberg C Vodroffs Tværgade"),
				new KeyValuePair<string,string>("1910","Frederiksberg C Danasvej"),
				new KeyValuePair<string,string>("1911","Frederiksberg C Niels Ebbesens Vej"),
				new KeyValuePair<string,string>("1912","Frederiksberg C Svend Trøsts Vej"),
				new KeyValuePair<string,string>("1913","Frederiksberg C Carl Plougs Vej"),
				new KeyValuePair<string,string>("1914","Frederiksberg C Vodroffslund"),
				new KeyValuePair<string,string>("1915","Frederiksberg C Danas Plads"),
				new KeyValuePair<string,string>("1916","Frederiksberg C Norsvej"),
				new KeyValuePair<string,string>("1917","Frederiksberg C Sveasvej"),
				new KeyValuePair<string,string>("1920","Frederiksberg C Forchhammersvej"),
				new KeyValuePair<string,string>("1921","Frederiksberg C Sankt Markus Plads"),
				new KeyValuePair<string,string>("1922","Frederiksberg C Sankt Markus Alle"),
				new KeyValuePair<string,string>("1923","Frederiksberg C Johnstrups Alle"),
				new KeyValuePair<string,string>("1924","Frederiksberg C Steenstrups Alle"),
				new KeyValuePair<string,string>("1925","Frederiksberg C Julius Thomsens Plads"),
				new KeyValuePair<string,string>("1926","Frederiksberg C Martinsvej"),
				new KeyValuePair<string,string>("1927","Frederiksberg C Suomisvej"),
				new KeyValuePair<string,string>("1928","Frederiksberg C Filippavej"),
				new KeyValuePair<string,string>("1931","Frederiksberg C Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("1950","Frederiksberg C Hostrupsvej"),
				new KeyValuePair<string,string>("1951","Frederiksberg C Christian Richardts Vej"),
				new KeyValuePair<string,string>("1952","Frederiksberg C Falkonervænget"),
				new KeyValuePair<string,string>("1953","Frederiksberg C Sankt Nikolaj Vej"),
				new KeyValuePair<string,string>("1954","Frederiksberg C Hostrups Have"),
				new KeyValuePair<string,string>("1955","Frederiksberg C Dr. Abildgaards Alle"),
				new KeyValuePair<string,string>("1956","Frederiksberg C L.I. Brandes Alle"),
				new KeyValuePair<string,string>("1957","Frederiksberg C N.J. Fjords Alle"),
				new KeyValuePair<string,string>("1958","Frederiksberg C Rolighedsvej"),
				new KeyValuePair<string,string>("1959","Frederiksberg C Falkonergårdsvej"),
				new KeyValuePair<string,string>("1960","Frederiksberg C Åboulevard 15-55"),
				new KeyValuePair<string,string>("1961","Frederiksberg C J.M. Thieles Vej"),
				new KeyValuePair<string,string>("1962","Frederiksberg C Fuglevangsvej"),
				new KeyValuePair<string,string>("1963","Frederiksberg C Bille Brahes Vej"),
				new KeyValuePair<string,string>("1964","Frederiksberg C Ingemannsvej"),
				new KeyValuePair<string,string>("1965","Frederiksberg C Erik Menveds Vej"),
				new KeyValuePair<string,string>("1966","Frederiksberg C Steenwinkelsvej"),
				new KeyValuePair<string,string>("1967","Frederiksberg C Svanemosegårdsvej"),
				new KeyValuePair<string,string>("1970","Frederiksberg C Rosenørns Alle 1-67 + 20-70"),
				new KeyValuePair<string,string>("1971","Frederiksberg C Adolph Steens Alle"),
				new KeyValuePair<string,string>("1972","Frederiksberg C Worsaaesvej"),
				new KeyValuePair<string,string>("1973","Frederiksberg C Jakob Dannefærds Vej"),
				new KeyValuePair<string,string>("1974","Frederiksberg C Julius Thomsens Gade ulige nr."),
				new KeyValuePair<string,string>("2000","Frederiksberg "),
				new KeyValuePair<string,string>("210","Sandur "),
				new KeyValuePair<string,string>("2100","København Ø "),
				new KeyValuePair<string,string>("215","Sandur Postboks"),
				new KeyValuePair<string,string>("220","Skálavík "),
				new KeyValuePair<string,string>("2200","København N "),
				new KeyValuePair<string,string>("230","Húsavík "),
				new KeyValuePair<string,string>("2300","København S "),
				new KeyValuePair<string,string>("235","Dalur "),
				new KeyValuePair<string,string>("236","Skarvanes "),
				new KeyValuePair<string,string>("240","Skopun "),
				new KeyValuePair<string,string>("2400","København NV "),
				new KeyValuePair<string,string>("2412","Santa Claus/Julemanden "),
				new KeyValuePair<string,string>("2450","København SV "),
				new KeyValuePair<string,string>("2500","Valby "),
				new KeyValuePair<string,string>("260","Skúvoy "),
				new KeyValuePair<string,string>("2600","Glostrup "),
				new KeyValuePair<string,string>("2605","Brøndby "),
				new KeyValuePair<string,string>("2610","Rødovre "),
				new KeyValuePair<string,string>("2620","Albertslund "),
				new KeyValuePair<string,string>("2625","Vallensbæk "),
				new KeyValuePair<string,string>("2630","Taastrup "),
				new KeyValuePair<string,string>("2635","Ishøj "),
				new KeyValuePair<string,string>("2640","Hedehusene "),
				new KeyValuePair<string,string>("2650","Hvidovre "),
				new KeyValuePair<string,string>("2660","Brøndby Strand "),
				new KeyValuePair<string,string>("2665","Vallensbæk Strand "),
				new KeyValuePair<string,string>("2670","Greve "),
				new KeyValuePair<string,string>("2680","Solrød Strand "),
				new KeyValuePair<string,string>("2690","Karlslunde "),
				new KeyValuePair<string,string>("270","Nólsoy "),
				new KeyValuePair<string,string>("2700","Brønshøj "),
				new KeyValuePair<string,string>("2720","Vanløse "),
				new KeyValuePair<string,string>("2730","Herlev "),
				new KeyValuePair<string,string>("2740","Skovlunde "),
				new KeyValuePair<string,string>("2750","Ballerup "),
				new KeyValuePair<string,string>("2760","Måløv "),
				new KeyValuePair<string,string>("2765","Smørum "),
				new KeyValuePair<string,string>("2770","Kastrup "),
				new KeyValuePair<string,string>("2791","Dragør "),
				new KeyValuePair<string,string>("280","Hestur "),
				new KeyValuePair<string,string>("2800","Kongens Lyngby "),
				new KeyValuePair<string,string>("2820","Gentofte "),
				new KeyValuePair<string,string>("2830","Virum "),
				new KeyValuePair<string,string>("2840","Holte "),
				new KeyValuePair<string,string>("285","Koltur "),
				new KeyValuePair<string,string>("2850","Nærum "),
				new KeyValuePair<string,string>("286","Stóra Dimun "),
				new KeyValuePair<string,string>("2860","Søborg "),
				new KeyValuePair<string,string>("2870","Dyssegård "),
				new KeyValuePair<string,string>("2880","Bagsværd "),
				new KeyValuePair<string,string>("2900","Hellerup "),
				new KeyValuePair<string,string>("2920","Charlottenlund "),
				new KeyValuePair<string,string>("2930","Klampenborg "),
				new KeyValuePair<string,string>("2942","Skodsborg "),
				new KeyValuePair<string,string>("2950","Vedbæk "),
				new KeyValuePair<string,string>("2960","Rungsted Kyst "),
				new KeyValuePair<string,string>("2970","Hørsholm "),
				new KeyValuePair<string,string>("2980","Kokkedal "),
				new KeyValuePair<string,string>("2990","Nivå "),
				new KeyValuePair<string,string>("3000","Helsingør "),
				new KeyValuePair<string,string>("3050","Humlebæk "),
				new KeyValuePair<string,string>("3060","Espergærde "),
				new KeyValuePair<string,string>("3070","Snekkersten "),
				new KeyValuePair<string,string>("3080","Tikøb "),
				new KeyValuePair<string,string>("3100","Hornbæk "),
				new KeyValuePair<string,string>("3120","Dronningmølle "),
				new KeyValuePair<string,string>("3140","Ålsgårde "),
				new KeyValuePair<string,string>("3150","Hellebæk "),
				new KeyValuePair<string,string>("3200","Helsinge "),
				new KeyValuePair<string,string>("3210","Vejby "),
				new KeyValuePair<string,string>("3220","Tisvildeleje "),
				new KeyValuePair<string,string>("3230","Græsted "),
				new KeyValuePair<string,string>("3250","Gilleleje "),
				new KeyValuePair<string,string>("330","Stykkid "),
				new KeyValuePair<string,string>("3300","Frederiksværk "),
				new KeyValuePair<string,string>("3310","Ølsted "),
				new KeyValuePair<string,string>("3320","Skævinge "),
				new KeyValuePair<string,string>("3330","Gørløse "),
				new KeyValuePair<string,string>("335","Leynar "),
				new KeyValuePair<string,string>("336","Skællingur "),
				new KeyValuePair<string,string>("3360","Liseleje "),
				new KeyValuePair<string,string>("3370","Melby "),
				new KeyValuePair<string,string>("3390","Hundested "),
				new KeyValuePair<string,string>("340","Kvívík "),
				new KeyValuePair<string,string>("3400","Hillerød "),
				new KeyValuePair<string,string>("3450","Allerød "),
				new KeyValuePair<string,string>("3460","Birkerød "),
				new KeyValuePair<string,string>("3480","Fredensborg "),
				new KeyValuePair<string,string>("3490","Kvistgård "),
				new KeyValuePair<string,string>("350","Vestmanna "),
				new KeyValuePair<string,string>("3500","Værløse "),
				new KeyValuePair<string,string>("3520","Farum "),
				new KeyValuePair<string,string>("3540","Lynge "),
				new KeyValuePair<string,string>("355","Vestmanna Postboks"),
				new KeyValuePair<string,string>("3550","Slangerup "),
				new KeyValuePair<string,string>("358","Válur "),
				new KeyValuePair<string,string>("360","Sandavágur "),
				new KeyValuePair<string,string>("3600","Frederikssund "),
				new KeyValuePair<string,string>("3630","Jægerspris "),
				new KeyValuePair<string,string>("3650","Ølstykke "),
				new KeyValuePair<string,string>("3660","Stenløse "),
				new KeyValuePair<string,string>("3670","Veksø Sjælland "),
				new KeyValuePair<string,string>("370","Midvágur "),
				new KeyValuePair<string,string>("3700","Rønne "),
				new KeyValuePair<string,string>("3720","Aakirkeby "),
				new KeyValuePair<string,string>("3730","Nexø "),
				new KeyValuePair<string,string>("3740","Svaneke "),
				new KeyValuePair<string,string>("375","Midvágur Postboks"),
				new KeyValuePair<string,string>("3751","Østermarie "),
				new KeyValuePair<string,string>("3760","Gudhjem "),
				new KeyValuePair<string,string>("3770","Allinge "),
				new KeyValuePair<string,string>("3782","Klemensker "),
				new KeyValuePair<string,string>("3790","Hasle "),
				new KeyValuePair<string,string>("380","Sørvágur "),
				new KeyValuePair<string,string>("385","Vatnsoyrar "),
				new KeyValuePair<string,string>("386","Bøur "),
				new KeyValuePair<string,string>("387","Gásadalur "),
				new KeyValuePair<string,string>("388","Mykines "),
				new KeyValuePair<string,string>("3900","Nuuk "),
				new KeyValuePair<string,string>("3905","Nuussuaq "),
				new KeyValuePair<string,string>("3910","Kangerlussuaq "),
				new KeyValuePair<string,string>("3911","Sisimiut "),
				new KeyValuePair<string,string>("3912","Maniitsoq "),
				new KeyValuePair<string,string>("3913","Tasiilaq "),
				new KeyValuePair<string,string>("3915","Kulusuk "),
				new KeyValuePair<string,string>("3919","Alluitsup Paa "),
				new KeyValuePair<string,string>("3920","Qaqortoq "),
				new KeyValuePair<string,string>("3921","Narsaq "),
				new KeyValuePair<string,string>("3922","Nanortalik "),
				new KeyValuePair<string,string>("3923","Narsarsuaq "),
				new KeyValuePair<string,string>("3924","Ikerasassuaq "),
				new KeyValuePair<string,string>("3930","Kangilinnguit "),
				new KeyValuePair<string,string>("3932","Arsuk "),
				new KeyValuePair<string,string>("3940","Paamiut "),
				new KeyValuePair<string,string>("3950","Aasiaat "),
				new KeyValuePair<string,string>("3951","Qasigiannguit "),
				new KeyValuePair<string,string>("3952","Ilulissat "),
				new KeyValuePair<string,string>("3953","Qeqertarsuaq "),
				new KeyValuePair<string,string>("3955","Kangaatsiaq "),
				new KeyValuePair<string,string>("3961","Uummannaq "),
				new KeyValuePair<string,string>("3962","Upernavik "),
				new KeyValuePair<string,string>("3964","Qaarsut "),
				new KeyValuePair<string,string>("3970","Pituffik "),
				new KeyValuePair<string,string>("3971","Qaanaaq "),
				new KeyValuePair<string,string>("3972","Station Nord "),
				new KeyValuePair<string,string>("3980","Ittoqqortoormiit "),
				new KeyValuePair<string,string>("3982","Mestersvig "),
				new KeyValuePair<string,string>("3984","Danmarkshavn "),
				new KeyValuePair<string,string>("3985","Constable Pynt "),
				new KeyValuePair<string,string>("3992","Slædepatruljen Sirius "),
				new KeyValuePair<string,string>("400","Oyrarbakki "),
				new KeyValuePair<string,string>("4000","Roskilde "),
				new KeyValuePair<string,string>("4030","Tune "),
				new KeyValuePair<string,string>("4040","Jyllinge "),
				new KeyValuePair<string,string>("405","Oyrarbakki Postboks"),
				new KeyValuePair<string,string>("4050","Skibby "),
				new KeyValuePair<string,string>("4060","Kirke Såby "),
				new KeyValuePair<string,string>("4070","Kirke Hyllinge "),
				new KeyValuePair<string,string>("410","Kollafjørdur "),
				new KeyValuePair<string,string>("4100","Ringsted "),
				new KeyValuePair<string,string>("4129","Ringsted Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("4130","Viby Sjælland "),
				new KeyValuePair<string,string>("4140","Borup "),
				new KeyValuePair<string,string>("415","Oyrareingir "),
				new KeyValuePair<string,string>("416","Signabøur "),
				new KeyValuePair<string,string>("4160","Herlufmagle "),
				new KeyValuePair<string,string>("4171","Glumsø "),
				new KeyValuePair<string,string>("4173","Fjenneslev "),
				new KeyValuePair<string,string>("4174","Jystrup Midtsj "),
				new KeyValuePair<string,string>("4180","Sorø "),
				new KeyValuePair<string,string>("4190","Munke Bjergby "),
				new KeyValuePair<string,string>("420","Hósvík "),
				new KeyValuePair<string,string>("4200","Slagelse "),
				new KeyValuePair<string,string>("4220","Korsør "),
				new KeyValuePair<string,string>("4230","Skælskør "),
				new KeyValuePair<string,string>("4241","Vemmelev "),
				new KeyValuePair<string,string>("4242","Boeslunde "),
				new KeyValuePair<string,string>("4243","Rude "),
				new KeyValuePair<string,string>("4250","Fuglebjerg "),
				new KeyValuePair<string,string>("4261","Dalmose "),
				new KeyValuePair<string,string>("4262","Sandved "),
				new KeyValuePair<string,string>("4270","Høng "),
				new KeyValuePair<string,string>("4281","Gørlev "),
				new KeyValuePair<string,string>("4291","Ruds Vedby "),
				new KeyValuePair<string,string>("4293","Dianalund "),
				new KeyValuePair<string,string>("4295","Stenlille "),
				new KeyValuePair<string,string>("4296","Nyrup "),
				new KeyValuePair<string,string>("430","Hvalvík "),
				new KeyValuePair<string,string>("4300","Holbæk "),
				new KeyValuePair<string,string>("4320","Lejre "),
				new KeyValuePair<string,string>("4330","Hvalsø "),
				new KeyValuePair<string,string>("4340","Tølløse "),
				new KeyValuePair<string,string>("435","Streymnes "),
				new KeyValuePair<string,string>("4350","Ugerløse "),
				new KeyValuePair<string,string>("436","Saksun "),
				new KeyValuePair<string,string>("4360","Kirke Eskilstrup "),
				new KeyValuePair<string,string>("437","Nesvík "),
				new KeyValuePair<string,string>("4370","Store Merløse "),
				new KeyValuePair<string,string>("438","Langasandur "),
				new KeyValuePair<string,string>("4390","Vipperød "),
				new KeyValuePair<string,string>("440","Haldarsvík "),
				new KeyValuePair<string,string>("4400","Kalundborg "),
				new KeyValuePair<string,string>("4420","Regstrup "),
				new KeyValuePair<string,string>("4440","Mørkøv "),
				new KeyValuePair<string,string>("445","Tjørnuvík "),
				new KeyValuePair<string,string>("4450","Jyderup "),
				new KeyValuePair<string,string>("4460","Snertinge "),
				new KeyValuePair<string,string>("4470","Svebølle "),
				new KeyValuePair<string,string>("4480","Store Fuglede "),
				new KeyValuePair<string,string>("4490","Jerslev Sjælland "),
				new KeyValuePair<string,string>("450","Oyri "),
				new KeyValuePair<string,string>("4500","Nykøbing Sj "),
				new KeyValuePair<string,string>("4520","Svinninge "),
				new KeyValuePair<string,string>("4532","Gislinge "),
				new KeyValuePair<string,string>("4534","Hørve "),
				new KeyValuePair<string,string>("4540","Fårevejle "),
				new KeyValuePair<string,string>("4550","Asnæs "),
				new KeyValuePair<string,string>("4560","Vig "),
				new KeyValuePair<string,string>("4571","Grevinge "),
				new KeyValuePair<string,string>("4572","Nørre Asmindrup "),
				new KeyValuePair<string,string>("4573","Højby "),
				new KeyValuePair<string,string>("4581","Rørvig "),
				new KeyValuePair<string,string>("4583","Sjællands Odde "),
				new KeyValuePair<string,string>("4591","Føllenslev "),
				new KeyValuePair<string,string>("4592","Sejerø "),
				new KeyValuePair<string,string>("4593","Eskebjerg "),
				new KeyValuePair<string,string>("460","Nordskáli "),
				new KeyValuePair<string,string>("4600","Køge "),
				new KeyValuePair<string,string>("4621","Gadstrup "),
				new KeyValuePair<string,string>("4622","Havdrup "),
				new KeyValuePair<string,string>("4623","Lille Skensved "),
				new KeyValuePair<string,string>("4632","Bjæverskov "),
				new KeyValuePair<string,string>("4640","Faxe "),
				new KeyValuePair<string,string>("465","Svináir "),
				new KeyValuePair<string,string>("4652","Hårlev "),
				new KeyValuePair<string,string>("4653","Karise "),
				new KeyValuePair<string,string>("4654","Faxe Ladeplads "),
				new KeyValuePair<string,string>("466","Ljósá "),
				new KeyValuePair<string,string>("4660","Store Heddinge "),
				new KeyValuePair<string,string>("4671","Strøby "),
				new KeyValuePair<string,string>("4672","Klippinge "),
				new KeyValuePair<string,string>("4673","Rødvig Stevns "),
				new KeyValuePair<string,string>("4681","Herfølge "),
				new KeyValuePair<string,string>("4682","Tureby "),
				new KeyValuePair<string,string>("4683","Rønnede "),
				new KeyValuePair<string,string>("4684","Holmegaard "),
				new KeyValuePair<string,string>("4690","Haslev "),
				new KeyValuePair<string,string>("470","Eidi "),
				new KeyValuePair<string,string>("4700","Næstved "),
				new KeyValuePair<string,string>("4720","Præstø "),
				new KeyValuePair<string,string>("4733","Tappernøje "),
				new KeyValuePair<string,string>("4735","Mern "),
				new KeyValuePair<string,string>("4736","Karrebæksminde "),
				new KeyValuePair<string,string>("475","Funningur "),
				new KeyValuePair<string,string>("4750","Lundby "),
				new KeyValuePair<string,string>("476","Gjógv "),
				new KeyValuePair<string,string>("4760","Vordingborg "),
				new KeyValuePair<string,string>("477","Funningsfjørdur "),
				new KeyValuePair<string,string>("4771","Kalvehave "),
				new KeyValuePair<string,string>("4772","Langebæk "),
				new KeyValuePair<string,string>("4773","Stensved "),
				new KeyValuePair<string,string>("478","Elduvík "),
				new KeyValuePair<string,string>("4780","Stege "),
				new KeyValuePair<string,string>("4791","Borre "),
				new KeyValuePair<string,string>("4792","Askeby "),
				new KeyValuePair<string,string>("4793","Bogø By "),
				new KeyValuePair<string,string>("480","Skáli "),
				new KeyValuePair<string,string>("4800","Nykøbing F "),
				new KeyValuePair<string,string>("4840","Nørre Alslev "),
				new KeyValuePair<string,string>("485","Skálafjørdur "),
				new KeyValuePair<string,string>("4850","Stubbekøbing "),
				new KeyValuePair<string,string>("4862","Guldborg "),
				new KeyValuePair<string,string>("4863","Eskilstrup "),
				new KeyValuePair<string,string>("4871","Horbelev "),
				new KeyValuePair<string,string>("4872","Idestrup "),
				new KeyValuePair<string,string>("4873","Væggerløse "),
				new KeyValuePair<string,string>("4874","Gedser "),
				new KeyValuePair<string,string>("4880","Nysted "),
				new KeyValuePair<string,string>("4891","Toreby L "),
				new KeyValuePair<string,string>("4892","Kettinge "),
				new KeyValuePair<string,string>("4894","Øster Ulslev "),
				new KeyValuePair<string,string>("4895","Errindlev "),
				new KeyValuePair<string,string>("490","Strendur "),
				new KeyValuePair<string,string>("4900","Nakskov "),
				new KeyValuePair<string,string>("4912","Harpelunde "),
				new KeyValuePair<string,string>("4913","Horslunde "),
				new KeyValuePair<string,string>("4920","Søllested "),
				new KeyValuePair<string,string>("4930","Maribo "),
				new KeyValuePair<string,string>("494","Innan Glyvur "),
				new KeyValuePair<string,string>("4941","Bandholm "),
				new KeyValuePair<string,string>("4943","Torrig L "),
				new KeyValuePair<string,string>("4944","Fejø "),
				new KeyValuePair<string,string>("495","Kolbanargjógv "),
				new KeyValuePair<string,string>("4951","Nørreballe "),
				new KeyValuePair<string,string>("4952","Stokkemarke "),
				new KeyValuePair<string,string>("4953","Vesterborg "),
				new KeyValuePair<string,string>("496","Morskranes "),
				new KeyValuePair<string,string>("4960","Holeby "),
				new KeyValuePair<string,string>("497","Selatrad "),
				new KeyValuePair<string,string>("4970","Rødby "),
				new KeyValuePair<string,string>("4983","Dannemare "),
				new KeyValuePair<string,string>("4990","Sakskøbing "),
				new KeyValuePair<string,string>("4992","Midtsjælland USF P"),
				new KeyValuePair<string,string>("5000","Odense C "),
				new KeyValuePair<string,string>("5029","Odense C Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("510","Gøta "),
				new KeyValuePair<string,string>("5100","Odense C Postboks"),
				new KeyValuePair<string,string>("511","Gøtugjógv "),
				new KeyValuePair<string,string>("512","Nordragøta "),
				new KeyValuePair<string,string>("513","Sydrugøta "),
				new KeyValuePair<string,string>("515","Gøta Postboks"),
				new KeyValuePair<string,string>("520","Leirvík "),
				new KeyValuePair<string,string>("5200","Odense V "),
				new KeyValuePair<string,string>("5210","Odense NV "),
				new KeyValuePair<string,string>("5220","Odense SØ "),
				new KeyValuePair<string,string>("5230","Odense M "),
				new KeyValuePair<string,string>("5240","Odense NØ "),
				new KeyValuePair<string,string>("5250","Odense SV "),
				new KeyValuePair<string,string>("5260","Odense S "),
				new KeyValuePair<string,string>("5270","Odense N "),
				new KeyValuePair<string,string>("5290","Marslev "),
				new KeyValuePair<string,string>("530","Fuglafjørdur "),
				new KeyValuePair<string,string>("5300","Kerteminde "),
				new KeyValuePair<string,string>("5320","Agedrup "),
				new KeyValuePair<string,string>("5330","Munkebo "),
				new KeyValuePair<string,string>("535","Fuglafjørdur Postboks"),
				new KeyValuePair<string,string>("5350","Rynkeby "),
				new KeyValuePair<string,string>("5370","Mesinge "),
				new KeyValuePair<string,string>("5380","Dalby "),
				new KeyValuePair<string,string>("5390","Martofte "),
				new KeyValuePair<string,string>("5400","Bogense "),
				new KeyValuePair<string,string>("5450","Otterup "),
				new KeyValuePair<string,string>("5462","Morud "),
				new KeyValuePair<string,string>("5463","Harndrup "),
				new KeyValuePair<string,string>("5464","Brenderup Fyn "),
				new KeyValuePair<string,string>("5466","Asperup "),
				new KeyValuePair<string,string>("5471","Søndersø "),
				new KeyValuePair<string,string>("5474","Veflinge "),
				new KeyValuePair<string,string>("5485","Skamby "),
				new KeyValuePair<string,string>("5491","Blommenslyst "),
				new KeyValuePair<string,string>("5492","Vissenbjerg "),
				new KeyValuePair<string,string>("5500","Middelfart "),
				new KeyValuePair<string,string>("5540","Ullerslev "),
				new KeyValuePair<string,string>("5550","Langeskov "),
				new KeyValuePair<string,string>("5560","Aarup "),
				new KeyValuePair<string,string>("5580","Nørre Aaby "),
				new KeyValuePair<string,string>("5591","Gelsted "),
				new KeyValuePair<string,string>("5592","Ejby "),
				new KeyValuePair<string,string>("5600","Faaborg "),
				new KeyValuePair<string,string>("5610","Assens "),
				new KeyValuePair<string,string>("5620","Glamsbjerg "),
				new KeyValuePair<string,string>("5631","Ebberup "),
				new KeyValuePair<string,string>("5642","Millinge "),
				new KeyValuePair<string,string>("5672","Broby "),
				new KeyValuePair<string,string>("5683","Haarby "),
				new KeyValuePair<string,string>("5690","Tommerup "),
				new KeyValuePair<string,string>("5700","Svendborg "),
				new KeyValuePair<string,string>("5750","Ringe "),
				new KeyValuePair<string,string>("5762","Vester Skerninge "),
				new KeyValuePair<string,string>("5771","Stenstrup "),
				new KeyValuePair<string,string>("5772","Kværndrup "),
				new KeyValuePair<string,string>("5792","Årslev "),
				new KeyValuePair<string,string>("5800","Nyborg "),
				new KeyValuePair<string,string>("5853","Ørbæk "),
				new KeyValuePair<string,string>("5854","Gislev "),
				new KeyValuePair<string,string>("5856","Ryslinge "),
				new KeyValuePair<string,string>("5863","Ferritslev Fyn "),
				new KeyValuePair<string,string>("5871","Frørup "),
				new KeyValuePair<string,string>("5874","Hesselager "),
				new KeyValuePair<string,string>("5881","Skårup Fyn "),
				new KeyValuePair<string,string>("5882","Vejstrup "),
				new KeyValuePair<string,string>("5883","Oure "),
				new KeyValuePair<string,string>("5884","Gudme "),
				new KeyValuePair<string,string>("5892","Gudbjerg Sydfyn "),
				new KeyValuePair<string,string>("5900","Rudkøbing "),
				new KeyValuePair<string,string>("5932","Humble "),
				new KeyValuePair<string,string>("5935","Bagenkop "),
				new KeyValuePair<string,string>("5953","Tranekær "),
				new KeyValuePair<string,string>("5960","Marstal "),
				new KeyValuePair<string,string>("5970","Ærøskøbing "),
				new KeyValuePair<string,string>("5985","Søby Ærø "),
				new KeyValuePair<string,string>("600","Saltangará "),
				new KeyValuePair<string,string>("6000","Kolding "),
				new KeyValuePair<string,string>("6040","Egtved "),
				new KeyValuePair<string,string>("6051","Almind "),
				new KeyValuePair<string,string>("6052","Viuf "),
				new KeyValuePair<string,string>("6064","Jordrup "),
				new KeyValuePair<string,string>("6070","Christiansfeld "),
				new KeyValuePair<string,string>("6091","Bjert "),
				new KeyValuePair<string,string>("6092","Sønder Stenderup "),
				new KeyValuePair<string,string>("6093","Sjølund "),
				new KeyValuePair<string,string>("6094","Hejls "),
				new KeyValuePair<string,string>("610","Saltangará Postboks"),
				new KeyValuePair<string,string>("6100","Haderslev "),
				new KeyValuePair<string,string>("620","Runavík "),
				new KeyValuePair<string,string>("6200","Aabenraa "),
				new KeyValuePair<string,string>("6230","Rødekro "),
				new KeyValuePair<string,string>("6240","Løgumkloster "),
				new KeyValuePair<string,string>("625","Glyvrar "),
				new KeyValuePair<string,string>("626","Lambareidi "),
				new KeyValuePair<string,string>("6261","Bredebro "),
				new KeyValuePair<string,string>("627","Lambi "),
				new KeyValuePair<string,string>("6270","Tønder "),
				new KeyValuePair<string,string>("6280","Højer "),
				new KeyValuePair<string,string>("6300","Gråsten "),
				new KeyValuePair<string,string>("6310","Broager "),
				new KeyValuePair<string,string>("6320","Egernsund "),
				new KeyValuePair<string,string>("6330","Padborg "),
				new KeyValuePair<string,string>("6340","Kruså "),
				new KeyValuePair<string,string>("6360","Tinglev "),
				new KeyValuePair<string,string>("6372","Bylderup-Bov "),
				new KeyValuePair<string,string>("6392","Bolderslev "),
				new KeyValuePair<string,string>("640","Rituvík "),
				new KeyValuePair<string,string>("6400","Sønderborg "),
				new KeyValuePair<string,string>("6430","Nordborg "),
				new KeyValuePair<string,string>("6440","Augustenborg "),
				new KeyValuePair<string,string>("645","Æduvík "),
				new KeyValuePair<string,string>("6470","Sydals "),
				new KeyValuePair<string,string>("650","Toftir "),
				new KeyValuePair<string,string>("6500","Vojens "),
				new KeyValuePair<string,string>("6510","Gram "),
				new KeyValuePair<string,string>("6520","Toftlund "),
				new KeyValuePair<string,string>("6534","Agerskov "),
				new KeyValuePair<string,string>("6535","Branderup J "),
				new KeyValuePair<string,string>("6541","Bevtoft "),
				new KeyValuePair<string,string>("655","Nes, Eysturoy "),
				new KeyValuePair<string,string>("656","Saltnes "),
				new KeyValuePair<string,string>("6560","Sommersted "),
				new KeyValuePair<string,string>("6580","Vamdrup "),
				new KeyValuePair<string,string>("660","Søldarfjørdur "),
				new KeyValuePair<string,string>("6600","Vejen "),
				new KeyValuePair<string,string>("6621","Gesten "),
				new KeyValuePair<string,string>("6622","Bække "),
				new KeyValuePair<string,string>("6623","Vorbasse "),
				new KeyValuePair<string,string>("6630","Rødding "),
				new KeyValuePair<string,string>("6640","Lunderskov "),
				new KeyValuePair<string,string>("665","Skipanes "),
				new KeyValuePair<string,string>("6650","Brørup "),
				new KeyValuePair<string,string>("666","Gøtueidi "),
				new KeyValuePair<string,string>("6660","Lintrup "),
				new KeyValuePair<string,string>("6670","Holsted "),
				new KeyValuePair<string,string>("6682","Hovborg "),
				new KeyValuePair<string,string>("6683","Føvling "),
				new KeyValuePair<string,string>("6690","Gørding "),
				new KeyValuePair<string,string>("6700","Esbjerg "),
				new KeyValuePair<string,string>("6701","Esbjerg Postboks"),
				new KeyValuePair<string,string>("6705","Esbjerg Ø "),
				new KeyValuePair<string,string>("6710","Esbjerg V "),
				new KeyValuePair<string,string>("6715","Esbjerg N "),
				new KeyValuePair<string,string>("6720","Fanø "),
				new KeyValuePair<string,string>("6731","Tjæreborg "),
				new KeyValuePair<string,string>("6740","Bramming "),
				new KeyValuePair<string,string>("6752","Glejbjerg "),
				new KeyValuePair<string,string>("6753","Agerbæk "),
				new KeyValuePair<string,string>("6760","Ribe "),
				new KeyValuePair<string,string>("6771","Gredstedbro "),
				new KeyValuePair<string,string>("6780","Skærbæk "),
				new KeyValuePair<string,string>("6792","Rømø "),
				new KeyValuePair<string,string>("6800","Varde "),
				new KeyValuePair<string,string>("6818","Årre "),
				new KeyValuePair<string,string>("6823","Ansager "),
				new KeyValuePair<string,string>("6830","Nørre Nebel "),
				new KeyValuePair<string,string>("6840","Oksbøl "),
				new KeyValuePair<string,string>("6851","Janderup Vestj "),
				new KeyValuePair<string,string>("6852","Billum "),
				new KeyValuePair<string,string>("6853","Vejers Strand "),
				new KeyValuePair<string,string>("6854","Henne "),
				new KeyValuePair<string,string>("6855","Outrup "),
				new KeyValuePair<string,string>("6857","Blåvand "),
				new KeyValuePair<string,string>("6862","Tistrup "),
				new KeyValuePair<string,string>("6870","Ølgod "),
				new KeyValuePair<string,string>("6880","Tarm "),
				new KeyValuePair<string,string>("6893","Hemmet "),
				new KeyValuePair<string,string>("690","Oyndarfjørdur "),
				new KeyValuePair<string,string>("6900","Skjern "),
				new KeyValuePair<string,string>("6920","Videbæk "),
				new KeyValuePair<string,string>("6933","Kibæk "),
				new KeyValuePair<string,string>("6940","Lem St "),
				new KeyValuePair<string,string>("695","Hellur "),
				new KeyValuePair<string,string>("6950","Ringkøbing "),
				new KeyValuePair<string,string>("6960","Hvide Sande "),
				new KeyValuePair<string,string>("6971","Spjald "),
				new KeyValuePair<string,string>("6973","Ørnhøj "),
				new KeyValuePair<string,string>("6980","Tim "),
				new KeyValuePair<string,string>("6990","Ulfborg "),
				new KeyValuePair<string,string>("700","Klaksvík "),
				new KeyValuePair<string,string>("7000","Fredericia "),
				new KeyValuePair<string,string>("7007","Fredericia"),
				new KeyValuePair<string,string>("7017","Taulov Pakkecenter"),
				new KeyValuePair<string,string>("7029","Fredericia Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("7080","Børkop "),
				new KeyValuePair<string,string>("710","Klaksvík Postboks"),
				new KeyValuePair<string,string>("7100","Vejle "),
				new KeyValuePair<string,string>("7120","Vejle Øst "),
				new KeyValuePair<string,string>("7130","Juelsminde "),
				new KeyValuePair<string,string>("7140","Stouby "),
				new KeyValuePair<string,string>("7150","Barrit "),
				new KeyValuePair<string,string>("7160","Tørring "),
				new KeyValuePair<string,string>("7171","Uldum "),
				new KeyValuePair<string,string>("7173","Vonge "),
				new KeyValuePair<string,string>("7182","Bredsten "),
				new KeyValuePair<string,string>("7183","Randbøl "),
				new KeyValuePair<string,string>("7184","Vandel "),
				new KeyValuePair<string,string>("7190","Billund "),
				new KeyValuePair<string,string>("7200","Grindsted "),
				new KeyValuePair<string,string>("725","Nordoyri "),
				new KeyValuePair<string,string>("7250","Hejnsvig "),
				new KeyValuePair<string,string>("726","Ánir "),
				new KeyValuePair<string,string>("7260","Sønder Omme "),
				new KeyValuePair<string,string>("727","Árnafjørdur "),
				new KeyValuePair<string,string>("7270","Stakroge "),
				new KeyValuePair<string,string>("7280","Sønder Felding "),
				new KeyValuePair<string,string>("730","Norddepil "),
				new KeyValuePair<string,string>("7300","Jelling "),
				new KeyValuePair<string,string>("7321","Gadbjerg "),
				new KeyValuePair<string,string>("7323","Give "),
				new KeyValuePair<string,string>("7330","Brande "),
				new KeyValuePair<string,string>("735","Depil "),
				new KeyValuePair<string,string>("736","Nordtoftir "),
				new KeyValuePair<string,string>("7361","Ejstrupholm "),
				new KeyValuePair<string,string>("7362","Hampen "),
				new KeyValuePair<string,string>("737","Múli "),
				new KeyValuePair<string,string>("740","Hvannasund "),
				new KeyValuePair<string,string>("7400","Herning "),
				new KeyValuePair<string,string>("7429","Herning Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("7430","Ikast "),
				new KeyValuePair<string,string>("7441","Bording "),
				new KeyValuePair<string,string>("7442","Engesvang "),
				new KeyValuePair<string,string>("7451","Sunds "),
				new KeyValuePair<string,string>("7470","Karup J "),
				new KeyValuePair<string,string>("7480","Vildbjerg "),
				new KeyValuePair<string,string>("7490","Aulum "),
				new KeyValuePair<string,string>("750","Vidareidi "),
				new KeyValuePair<string,string>("7500","Holstebro "),
				new KeyValuePair<string,string>("7540","Haderup "),
				new KeyValuePair<string,string>("7550","Sørvad "),
				new KeyValuePair<string,string>("7560","Hjerm "),
				new KeyValuePair<string,string>("7570","Vemb "),
				new KeyValuePair<string,string>("7600","Struer "),
				new KeyValuePair<string,string>("7620","Lemvig "),
				new KeyValuePair<string,string>("765","Svinoy "),
				new KeyValuePair<string,string>("7650","Bøvlingbjerg "),
				new KeyValuePair<string,string>("766","Kirkja "),
				new KeyValuePair<string,string>("7660","Bækmarksbro "),
				new KeyValuePair<string,string>("767","Hattarvík "),
				new KeyValuePair<string,string>("7673","Harboøre "),
				new KeyValuePair<string,string>("7680","Thyborøn "),
				new KeyValuePair<string,string>("7700","Thisted "),
				new KeyValuePair<string,string>("7730","Hanstholm "),
				new KeyValuePair<string,string>("7741","Frøstrup "),
				new KeyValuePair<string,string>("7742","Vesløs "),
				new KeyValuePair<string,string>("7752","Snedsted "),
				new KeyValuePair<string,string>("7755","Bedsted Thy "),
				new KeyValuePair<string,string>("7760","Hurup Thy "),
				new KeyValuePair<string,string>("7770","Vestervig "),
				new KeyValuePair<string,string>("7790","Thyholm "),
				new KeyValuePair<string,string>("780","Kunoy "),
				new KeyValuePair<string,string>("7800","Skive "),
				new KeyValuePair<string,string>("7830","Vinderup "),
				new KeyValuePair<string,string>("7840","Højslev "),
				new KeyValuePair<string,string>("785","Haraldssund "),
				new KeyValuePair<string,string>("7850","Stoholm Jyll "),
				new KeyValuePair<string,string>("7860","Spøttrup "),
				new KeyValuePair<string,string>("7870","Roslev "),
				new KeyValuePair<string,string>("7884","Fur "),
				new KeyValuePair<string,string>("7900","Nykøbing M "),
				new KeyValuePair<string,string>("795","Sydradalur, Kalsoy "),
				new KeyValuePair<string,string>("7950","Erslev "),
				new KeyValuePair<string,string>("796","Húsar "),
				new KeyValuePair<string,string>("7960","Karby "),
				new KeyValuePair<string,string>("797","Mikladalur "),
				new KeyValuePair<string,string>("7970","Redsted M "),
				new KeyValuePair<string,string>("798","Trøllanes "),
				new KeyValuePair<string,string>("7980","Vils "),
				new KeyValuePair<string,string>("7990","Øster Assels "),
				new KeyValuePair<string,string>("7992","Sydjylland/Fyn USF P"),
				new KeyValuePair<string,string>("7993","Sydjylland/Fyn USF B"),
				new KeyValuePair<string,string>("7996","Fakturaservice"),
				new KeyValuePair<string,string>("7997","Fakturascanning"),
				new KeyValuePair<string,string>("7999","Kommunepost"),
				new KeyValuePair<string,string>("800","Tvøroyri "),
				new KeyValuePair<string,string>("8000","Aarhus C "),
				new KeyValuePair<string,string>("810","Tvøroyri Postboks"),
				new KeyValuePair<string,string>("8100","Aarhus C Postboks"),
				new KeyValuePair<string,string>("8200","Aarhus N "),
				new KeyValuePair<string,string>("8210","Aarhus V "),
				new KeyValuePair<string,string>("8220","Brabrand "),
				new KeyValuePair<string,string>("8229","Risskov Ø Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("8230","Åbyhøj "),
				new KeyValuePair<string,string>("8240","Risskov "),
				new KeyValuePair<string,string>("8245","Risskov Ø"),
				new KeyValuePair<string,string>("825","Frodba "),
				new KeyValuePair<string,string>("8250","Egå "),
				new KeyValuePair<string,string>("826","Trongisvágur "),
				new KeyValuePair<string,string>("8260","Viby J "),
				new KeyValuePair<string,string>("827","Øravík "),
				new KeyValuePair<string,string>("8270","Højbjerg "),
				new KeyValuePair<string,string>("8300","Odder "),
				new KeyValuePair<string,string>("8305","Samsø "),
				new KeyValuePair<string,string>("8310","Tranbjerg J "),
				new KeyValuePair<string,string>("8320","Mårslet "),
				new KeyValuePair<string,string>("8330","Beder "),
				new KeyValuePair<string,string>("8340","Malling "),
				new KeyValuePair<string,string>("8350","Hundslund "),
				new KeyValuePair<string,string>("8355","Solbjerg "),
				new KeyValuePair<string,string>("8361","Hasselager "),
				new KeyValuePair<string,string>("8362","Hørning "),
				new KeyValuePair<string,string>("8370","Hadsten "),
				new KeyValuePair<string,string>("8380","Trige "),
				new KeyValuePair<string,string>("8381","Tilst "),
				new KeyValuePair<string,string>("8382","Hinnerup "),
				new KeyValuePair<string,string>("8400","Ebeltoft "),
				new KeyValuePair<string,string>("8410","Rønde "),
				new KeyValuePair<string,string>("8420","Knebel "),
				new KeyValuePair<string,string>("8444","Balle "),
				new KeyValuePair<string,string>("8450","Hammel "),
				new KeyValuePair<string,string>("8462","Harlev J "),
				new KeyValuePair<string,string>("8464","Galten "),
				new KeyValuePair<string,string>("8471","Sabro "),
				new KeyValuePair<string,string>("8472","Sporup "),
				new KeyValuePair<string,string>("850","Hvalba "),
				new KeyValuePair<string,string>("8500","Grenaa "),
				new KeyValuePair<string,string>("8520","Lystrup "),
				new KeyValuePair<string,string>("8530","Hjortshøj "),
				new KeyValuePair<string,string>("8541","Skødstrup "),
				new KeyValuePair<string,string>("8543","Hornslet "),
				new KeyValuePair<string,string>("8544","Mørke "),
				new KeyValuePair<string,string>("8550","Ryomgård "),
				new KeyValuePair<string,string>("8560","Kolind "),
				new KeyValuePair<string,string>("8570","Trustrup "),
				new KeyValuePair<string,string>("8581","Nimtofte "),
				new KeyValuePair<string,string>("8585","Glesborg "),
				new KeyValuePair<string,string>("8586","Ørum Djurs "),
				new KeyValuePair<string,string>("8592","Anholt "),
				new KeyValuePair<string,string>("860","Sandvík "),
				new KeyValuePair<string,string>("8600","Silkeborg "),
				new KeyValuePair<string,string>("8620","Kjellerup "),
				new KeyValuePair<string,string>("8632","Lemming "),
				new KeyValuePair<string,string>("8641","Sorring "),
				new KeyValuePair<string,string>("8643","Ans By "),
				new KeyValuePair<string,string>("8653","Them "),
				new KeyValuePair<string,string>("8654","Bryrup "),
				new KeyValuePair<string,string>("8660","Skanderborg "),
				new KeyValuePair<string,string>("8670","Låsby "),
				new KeyValuePair<string,string>("8680","Ry "),
				new KeyValuePair<string,string>("870","Fámjin "),
				new KeyValuePair<string,string>("8700","Horsens "),
				new KeyValuePair<string,string>("8721","Daugård "),
				new KeyValuePair<string,string>("8722","Hedensted "),
				new KeyValuePair<string,string>("8723","Løsning "),
				new KeyValuePair<string,string>("8732","Hovedgård "),
				new KeyValuePair<string,string>("8740","Brædstrup "),
				new KeyValuePair<string,string>("8751","Gedved "),
				new KeyValuePair<string,string>("8752","Østbirk "),
				new KeyValuePair<string,string>("8762","Flemming "),
				new KeyValuePair<string,string>("8763","Rask Mølle "),
				new KeyValuePair<string,string>("8765","Klovborg "),
				new KeyValuePair<string,string>("8766","Nørre Snede "),
				new KeyValuePair<string,string>("8781","Stenderup "),
				new KeyValuePair<string,string>("8783","Hornsyld "),
				new KeyValuePair<string,string>("8800","Viborg "),
				new KeyValuePair<string,string>("8830","Tjele "),
				new KeyValuePair<string,string>("8831","Løgstrup "),
				new KeyValuePair<string,string>("8832","Skals "),
				new KeyValuePair<string,string>("8840","Rødkærsbro "),
				new KeyValuePair<string,string>("8850","Bjerringbro "),
				new KeyValuePair<string,string>("8860","Ulstrup "),
				new KeyValuePair<string,string>("8870","Langå "),
				new KeyValuePair<string,string>("8881","Thorsø "),
				new KeyValuePair<string,string>("8882","Fårvang "),
				new KeyValuePair<string,string>("8883","Gjern "),
				new KeyValuePair<string,string>("8900","Randers C "),
				new KeyValuePair<string,string>("8920","Randers NV "),
				new KeyValuePair<string,string>("8930","Randers NØ "),
				new KeyValuePair<string,string>("8940","Randers SV "),
				new KeyValuePair<string,string>("8950","Ørsted "),
				new KeyValuePair<string,string>("8960","Randers SØ "),
				new KeyValuePair<string,string>("8961","Allingåbro "),
				new KeyValuePair<string,string>("8963","Auning "),
				new KeyValuePair<string,string>("8970","Havndal "),
				new KeyValuePair<string,string>("8981","Spentrup "),
				new KeyValuePair<string,string>("8983","Gjerlev J "),
				new KeyValuePair<string,string>("8990","Fårup "),
				new KeyValuePair<string,string>("900","Vágur "),
				new KeyValuePair<string,string>("9000","Aalborg "),
				new KeyValuePair<string,string>("9029","Aalborg Ufrankerede svarforsendelser"),
				new KeyValuePair<string,string>("910","Vágur Postboks"),
				new KeyValuePair<string,string>("9100","Aalborg Postboks"),
				new KeyValuePair<string,string>("9200","Aalborg SV "),
				new KeyValuePair<string,string>("9210","Aalborg SØ "),
				new KeyValuePair<string,string>("9220","Aalborg Øst "),
				new KeyValuePair<string,string>("9230","Svenstrup J "),
				new KeyValuePair<string,string>("9240","Nibe "),
				new KeyValuePair<string,string>("925","Nes, Vágur "),
				new KeyValuePair<string,string>("926","Lopra "),
				new KeyValuePair<string,string>("9260","Gistrup "),
				new KeyValuePair<string,string>("927","Akrar "),
				new KeyValuePair<string,string>("9270","Klarup "),
				new KeyValuePair<string,string>("928","Vikarbyrgi "),
				new KeyValuePair<string,string>("9280","Storvorde "),
				new KeyValuePair<string,string>("9293","Kongerslev "),
				new KeyValuePair<string,string>("9300","Sæby "),
				new KeyValuePair<string,string>("9310","Vodskov "),
				new KeyValuePair<string,string>("9320","Hjallerup "),
				new KeyValuePair<string,string>("9330","Dronninglund "),
				new KeyValuePair<string,string>("9340","Asaa "),
				new KeyValuePair<string,string>("9352","Dybvad "),
				new KeyValuePair<string,string>("9362","Gandrup "),
				new KeyValuePair<string,string>("9370","Hals "),
				new KeyValuePair<string,string>("9380","Vestbjerg "),
				new KeyValuePair<string,string>("9381","Sulsted "),
				new KeyValuePair<string,string>("9382","Tylstrup "),
				new KeyValuePair<string,string>("9400","Nørresundby "),
				new KeyValuePair<string,string>("9430","Vadum "),
				new KeyValuePair<string,string>("9440","Aabybro "),
				new KeyValuePair<string,string>("9460","Brovst "),
				new KeyValuePair<string,string>("9480","Løkken "),
				new KeyValuePair<string,string>("9490","Pandrup "),
				new KeyValuePair<string,string>("9492","Blokhus "),
				new KeyValuePair<string,string>("9493","Saltum "),
				new KeyValuePair<string,string>("950","Porkeri "),
				new KeyValuePair<string,string>("9500","Hobro "),
				new KeyValuePair<string,string>("9510","Arden "),
				new KeyValuePair<string,string>("9520","Skørping "),
				new KeyValuePair<string,string>("9530","Støvring "),
				new KeyValuePair<string,string>("9541","Suldrup "),
				new KeyValuePair<string,string>("9550","Mariager "),
				new KeyValuePair<string,string>("9560","Hadsund "),
				new KeyValuePair<string,string>("9574","Bælum "),
				new KeyValuePair<string,string>("9575","Terndrup "),
				new KeyValuePair<string,string>("960","Hov "),
				new KeyValuePair<string,string>("9600","Aars "),
				new KeyValuePair<string,string>("9610","Nørager "),
				new KeyValuePair<string,string>("9620","Aalestrup "),
				new KeyValuePair<string,string>("9631","Gedsted "),
				new KeyValuePair<string,string>("9632","Møldrup "),
				new KeyValuePair<string,string>("9640","Farsø "),
				new KeyValuePair<string,string>("9670","Løgstør "),
				new KeyValuePair<string,string>("9681","Ranum "),
				new KeyValuePair<string,string>("9690","Fjerritslev "),
				new KeyValuePair<string,string>("970","Sumba "),
				new KeyValuePair<string,string>("9700","Brønderslev "),
				new KeyValuePair<string,string>("9740","Jerslev J "),
				new KeyValuePair<string,string>("9750","Østervrå "),
				new KeyValuePair<string,string>("9760","Vrå "),
				new KeyValuePair<string,string>("9800","Hjørring "),
				new KeyValuePair<string,string>("9830","Tårs "),
				new KeyValuePair<string,string>("9850","Hirtshals "),
				new KeyValuePair<string,string>("9870","Sindal "),
				new KeyValuePair<string,string>("9881","Bindslev "),
				new KeyValuePair<string,string>("9900","Frederikshavn "),
				new KeyValuePair<string,string>("9940","Læsø "),
				new KeyValuePair<string,string>("9970","Strandby "),
				new KeyValuePair<string,string>("9981","Jerup "),
				new KeyValuePair<string,string>("9982","Ålbæk "),
				new KeyValuePair<string,string>("9990","Skagen "),
				new KeyValuePair<string,string>("9992","Jylland USF P"),
				new KeyValuePair<string,string>("9993","Jylland USF B"),
				new KeyValuePair<string,string>("9996","Fakturaservice "),
				new KeyValuePair<string,string>("9997","Fakturascanning"),
				new KeyValuePair<string,string>("9998","Borgerservice"),
			};
		}

		private static PostalCity _instance;
		public static PostalCity GetInstance()
		{
			if (_instance == null)
			{
				_instance = new PostalCity();
			}

			return _instance;
		}
	}
}
